import type { Question } from './questionsData';

export const questionsClaseC: Question[] = [
  {
    id: 1300,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Es obligatorio el uso de casco para el conductor y el pasajero de una motocicleta en Chile?',
    opciones: ['Solo para el conductor', 'Solo en carreteras', 'Sí, es obligatorio para ambos en todo momento', 'Solo si se circula a más de 60 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La Ley de Tránsito establece que tanto el conductor como el pasajero de una motocicleta deben usar casco protector certificado en todo momento de circulación. No usar casco constituye una infracción gravísima. El casco debe estar correctamente abrochado y ser del tipo aprobado por normas de seguridad vigentes.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1301,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuántos pasajeros puede llevar una motocicleta convencional?',
    opciones: ['Hasta 2 pasajeros', 'Solo 1 pasajero, siempre que el vehículo tenga asiento y estribos para acompañante', 'Ninguno, solo el conductor', 'Depende de la cilindrada'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una motocicleta convencional puede llevar solo un pasajero, siempre que cuente con asiento y estribos (apoyapiés) diseñados para el acompañante. El pasajero debe usar casco y no puede ir sentado de lado ni de pie. Llevar más pasajeros de los autorizados es una infracción grave.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1302,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Pueden las motocicletas circular entre filas de vehículos detenidos en Chile?',
    opciones: ['Sí, siempre está permitido', 'No, está prohibido circular entre filas de vehículos', 'Solo si los vehículos están completamente detenidos', 'Solo en autopistas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En Chile está prohibido que las motocicletas circulen entre filas de vehículos (lane splitting). Esta maniobra es peligrosa porque los conductores de automóviles no esperan que un vehículo circule entre ellos. Constituye una infracción grave y es una de las principales causas de accidentes de motociclistas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1303,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué cilindrada mínima debe tener una motocicleta para circular por autopistas en Chile?',
    opciones: ['50 cc', '100 cc', '150 cc', '250 cc'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Para circular por autopistas, una motocicleta debe tener una cilindrada mínima de 150 cc. Esto se debe a que los vehículos que circulan por autopistas deben poder desarrollar velocidades compatibles con el flujo vehicular. Las motocicletas de menor cilindrada no pueden alcanzar velocidades seguras para este tipo de vías.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1304,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Está permitido transportar niños menores de 5 años como pasajeros en una motocicleta?',
    opciones: ['Sí, con casco infantil', 'Sí, si van sujetos al conductor', 'No, está prohibido llevar menores de 5 años en motocicleta', 'Solo en trayectos cortos'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Está prohibido transportar niños menores de 5 años como pasajeros en motocicletas. Los menores no tienen la capacidad física ni la coordinación para mantenerse seguros en una motocicleta. Esta restricción busca proteger a los niños de los riesgos inherentes a la conducción en dos ruedas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1305,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué tipo de casco es el más seguro para conducir motocicleta?',
    opciones: ['Casco abierto (jet)', 'Casco integral (full face)', 'Casco tipo media concha', 'Cualquier casco es igual de seguro'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El casco integral (full face) es el más seguro porque protege toda la cabeza incluyendo la mandíbula y el mentón, zonas que reciben impactos en un alto porcentaje de accidentes. Debe estar certificado, tener visera transparente en buen estado y abrocharse correctamente con la correa de retención.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1306,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué indumentaria de protección es recomendable para conducir motocicleta además del casco?',
    opciones: ['Solo casco y guantes', 'Chaqueta con protecciones, guantes, botas y pantalón resistente', 'Ropa cómoda y liviana', 'Chaleco reflectante únicamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se recomienda usar chaqueta con protecciones en codos, hombros y espalda, guantes reforzados, botas que cubran los tobillos y pantalón con protección en rodillas. En caso de caída, la piel expuesta sufre abrasiones graves al contacto con el asfalto. El equipo de protección reduce significativamente la gravedad de las lesiones.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1307,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué es importante usar guantes al conducir una motocicleta?',
    opciones: ['Solo por comodidad', 'Protegen las manos en caso de caída y mejoran el agarre', 'Son obligatorios por ley', 'Solo son necesarios en invierno'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los guantes protegen las manos contra abrasiones en caso de caída, ya que instintivamente las manos son lo primero que toca el suelo. También mejoran el agarre en los mandos, protegen contra el frío que puede entorpecer los movimientos y contra insectos o piedras que pueden impactar durante la conducción.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1308,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la técnica correcta de frenado en motocicleta?',
    opciones: ['Usar solo el freno trasero', 'Usar solo el freno delantero', 'Aplicar ambos frenos simultáneamente de forma progresiva', 'Frenar bruscamente con el freno delantero'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La técnica correcta es aplicar ambos frenos simultáneamente de forma progresiva: el freno delantero aporta aproximadamente el 70% de la capacidad de frenado y el trasero el 30%. Frenar solo con el delantero puede causar que la rueda delantera se bloquee y se pierda el control. Frenar solo con el trasero alarga la distancia de frenado.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1309,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué ocurre si se frena bruscamente solo con el freno delantero en una motocicleta?',
    opciones: ['Se detiene más rápido y de forma segura', 'La rueda delantera puede bloquearse y el conductor salir despedido por encima del manillar', 'No pasa nada especial', 'La motocicleta se inclina hacia atrás'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al frenar bruscamente solo con el freno delantero, la rueda puede bloquearse provocando la pérdida de estabilidad. Si la rueda no se bloquea pero la frenada es muy intensa, la inercia puede levantar la rueda trasera y el conductor puede salir despedido por encima del manillar. Siempre se debe frenar de forma progresiva usando ambos frenos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1310,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe tomarse una curva en motocicleta?',
    opciones: ['Acelerando durante toda la curva', 'Reduciendo velocidad antes de la curva, inclinando la moto y acelerando suavemente a la salida', 'Frenando dentro de la curva', 'Manteniendo la moto completamente vertical'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La técnica correcta es reducir la velocidad antes de entrar a la curva, inclinar la motocicleta en la dirección del giro manteniendo la mirada hacia donde se quiere ir, y acelerar suavemente al salir de la curva. Frenar dentro de la curva puede causar pérdida de adherencia y una caída.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1311,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué es peligroso frenar dentro de una curva en motocicleta?',
    opciones: ['Porque la moto acelera automáticamente', 'Porque se reduce la adherencia del neumático y se puede perder tracción', 'No es peligroso si se hace suavemente', 'Porque los frenos no funcionan en curvas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al tomar una curva, los neumáticos ya están al límite de su adherencia por la fuerza lateral. Al frenar se suma la fuerza longitudinal, superando la capacidad de agarre del neumático, lo que puede causar un deslizamiento y caída. Por eso es fundamental ajustar la velocidad antes de entrar a la curva.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1312,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es el contramanillar (contrasteering) en motocicleta?',
    opciones: ['Girar el manillar en dirección contraria a la curva para iniciar la inclinación', 'Frenar con la rueda contraria a la curva', 'Usar el freno de mano en las curvas', 'Girar el manillar en la misma dirección de la curva'],
    respuestaCorrecta: 0,
    explicacionTexto: 'El contramanillar es la técnica por la cual, a velocidades superiores a 20-30 km/h, se empuja ligeramente el manillar en dirección contraria a la curva para iniciar la inclinación de la motocicleta. Por ejemplo, para girar a la derecha se empuja el manillar hacia la derecha (lo que lo gira ligeramente a la izquierda), provocando que la moto se incline a la derecha.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1313,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la posición correcta del cuerpo al conducir una motocicleta en línea recta?',
    opciones: ['Inclinado hacia adelante con los brazos rígidos', 'Erguido, con brazos ligeramente flexionados, rodillas pegadas al tanque y pies en los estribos', 'Recostado hacia atrás para mayor comodidad', 'Cualquier posición es correcta'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La posición correcta es mantener el cuerpo erguido, brazos ligeramente flexionados para absorber vibraciones, rodillas pegadas al tanque para mayor estabilidad, y pies apoyados en los estribos con la punta hacia adelante. Los brazos rígidos transmiten las irregularidades del camino y dificultan el control del manillar.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1314,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué efecto tiene el viento lateral en una motocicleta?',
    opciones: ['No afecta a las motocicletas', 'Puede desestabilizar la moto y desviarla de su trayectoria', 'Solo afecta a velocidades muy altas', 'Mejora la estabilidad de la moto'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El viento lateral puede desestabilizar significativamente una motocicleta debido a su menor peso y mayor superficie expuesta en relación a su base de apoyo. Es especialmente peligroso al salir de túneles, al pasar junto a camiones o en puentes elevados. Se debe reducir la velocidad y mantener un agarre firme del manillar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1315,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es el principal riesgo de visibilidad para un motociclista en el tránsito?',
    opciones: ['Los semáforos están muy altos', 'Los demás conductores pueden no ver la motocicleta por su menor tamaño', 'Las motos son demasiado rápidas para ser vistas', 'No hay riesgos especiales de visibilidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las motocicletas son más difíciles de detectar por otros conductores debido a su menor tamaño. Este fenómeno se conoce como "ceguera por inatención". Los motociclistas deben asumir que pueden no ser vistos y tomar medidas como usar ropa de alta visibilidad, mantener las luces encendidas y posicionarse en la parte visible del carril.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1316,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué se recomienda para aumentar la visibilidad del motociclista?',
    opciones: ['Usar bocina constantemente', 'Usar ropa de colores claros o reflectantes y llevar las luces siempre encendidas', 'Circular a alta velocidad para llamar la atención', 'No es posible aumentar la visibilidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para aumentar la visibilidad se recomienda usar ropa de colores claros o con elementos reflectantes, llevar siempre las luces encendidas (incluso de día), usar chaleco reflectante, posicionarse en la parte del carril donde sea más visible y evitar circular en los puntos ciegos de otros vehículos.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1317,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué son los puntos ciegos y por qué son especialmente peligrosos para los motociclistas?',
    opciones: ['Son zonas sin iluminación en la calle', 'Son áreas alrededor de un vehículo que el conductor no puede ver por los espejos, donde la moto puede desaparecer completamente', 'Son intersecciones sin semáforo', 'Son curvas cerradas sin visibilidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los puntos ciegos son áreas alrededor de un vehículo que no son visibles ni por los espejos retrovisores ni por la visión directa del conductor. Las motocicletas, por su tamaño reducido, pueden quedar completamente ocultas en estos puntos. Los motociclistas deben evitar circular en los puntos ciegos de otros vehículos y adelantar rápidamente cuando transiten por ellos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1318,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué distancia de seguimiento debe mantener un motociclista respecto al vehículo que lo precede?',
    opciones: ['La misma que un automóvil', 'Mayor que un automóvil, al menos 3 segundos', 'Menor que un automóvil por su capacidad de frenado', 'No importa la distancia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un motociclista debe mantener una distancia de seguimiento mayor que un automóvil, al menos 3 segundos. Esto se debe a que la motocicleta es más vulnerable a irregularidades en el pavimento, objetos en la vía y derrames de líquidos que un automóvil podría pasar sin problemas pero que son peligrosos para una moto.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1319,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué precaución especial debe tomar un motociclista al circular detrás de un camión?',
    opciones: ['Circular lo más cerca posible para protegerse del viento', 'Mantener mayor distancia porque el camión bloquea la visión y puede desprender objetos', 'No hay precauciones especiales', 'Adelantarlo inmediatamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al circular detrás de un camión, el motociclista debe mantener mayor distancia porque el camión bloquea completamente la visión de la vía adelante, puede desprender piedras u objetos de su carga, y genera turbulencias de aire. Además, el motociclista queda en el punto ciego del camionero, quien podría no verlo al frenar o maniobrar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1320,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo afecta la lluvia a la conducción en motocicleta?',
    opciones: ['No afecta significativamente', 'Reduce la adherencia, la visibilidad y aumenta la distancia de frenado', 'Solo afecta la visibilidad', 'Mejora el agarre de los neumáticos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La lluvia afecta gravemente la conducción en motocicleta: reduce la adherencia de los neumáticos (especialmente en los primeros minutos), disminuye la visibilidad, aumenta la distancia de frenado y hace resbaladizas las marcas viales pintadas, las tapas de alcantarilla y las líneas de demarcación. Se debe reducir significativamente la velocidad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1321,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué superficies son especialmente peligrosas para una motocicleta bajo lluvia?',
    opciones: ['Solo el asfalto mojado', 'Marcas viales pintadas, tapas de alcantarilla, rieles de tranvía y manchas de aceite', 'Solo las curvas', 'Ninguna superficie es peligrosa con neumáticos buenos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Bajo lluvia, las superficies más peligrosas para motocicletas son las marcas viales pintadas (paso de cebra, líneas de carril), tapas de alcantarilla metálicas, rieles de tranvía, manchas de aceite o combustible, y hojas secas. Estas superficies se vuelven extremadamente resbaladizas cuando están mojadas y pueden causar pérdida total de tracción.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1322,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la posición más segura del motociclista dentro del carril?',
    opciones: ['Siempre en el centro del carril', 'Varía según la situación: puede ser el tercio izquierdo, centro o tercio derecho', 'Siempre pegado al borde derecho', 'Siempre pegado al borde izquierdo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La posición dentro del carril debe variar según la situación. El tercio izquierdo ofrece mejor visibilidad y es visible para los demás. El centro puede tener acumulación de aceite y líquidos. El tercio derecho es útil para ver más allá de vehículos grandes. El motociclista debe elegir la posición que maximice su visibilidad y seguridad en cada momento.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1323,
    categoria: 'Mecánica Básica',
    pregunta: '¿Con qué frecuencia se debe revisar la presión de los neumáticos de una motocicleta?',
    opciones: ['Una vez al mes', 'Antes de cada viaje o al menos semanalmente', 'Solo cuando se ven desinflados', 'En cada revisión técnica'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La presión de los neumáticos debe revisarse antes de cada viaje o al menos semanalmente, siempre con los neumáticos fríos. Una motocicleta tiene solo dos puntos de contacto con el suelo, por lo que la presión correcta es crítica para la estabilidad, el frenado y la adherencia. La presión inadecuada puede causar desgaste irregular y pérdida de control.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1324,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué elementos debe revisar un motociclista antes de cada viaje?',
    opciones: ['Solo el nivel de combustible', 'Neumáticos, frenos, luces, aceite, cadena y espejos', 'Solo los frenos y las luces', 'Nada, la revisión técnica es suficiente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de cada viaje se debe hacer una inspección rápida que incluya: presión y estado de neumáticos, funcionamiento de frenos delantero y trasero, todas las luces (delantera, trasera, freno, señaleros), nivel de aceite, tensión y lubricación de la cadena, estado de los espejos retrovisores y nivel de combustible.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1325,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué sucede si la cadena de transmisión de una motocicleta está demasiado tensa?',
    opciones: ['La moto anda más rápido', 'Se desgastan prematuramente los piñones, la cadena y los rodamientos', 'No tiene ningún efecto', 'Mejora la tracción'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una cadena demasiado tensa causa desgaste prematuro de piñones, la propia cadena y los rodamientos del eje trasero. También genera mayor esfuerzo en la transmisión y puede romperse durante la marcha, lo que es extremadamente peligroso. La tensión debe ajustarse según las especificaciones del fabricante, dejando una holgura adecuada.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1326,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué sucede si la cadena de transmisión está demasiado floja?',
    opciones: ['La moto consume menos combustible', 'Puede salirse del piñón, golpear el motor o trabar la rueda trasera', 'Solo hace ruido pero no es peligroso', 'Mejora la comodidad del viaje'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una cadena demasiado floja puede salirse de los piñones durante la marcha, golpear el cárter del motor causando daños graves, o trabar la rueda trasera provocando una pérdida de control súbita. Además, genera golpeteo, desgaste irregular y transmisión de potencia ineficiente. La tensión correcta es fundamental para la seguridad.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1327,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál es la profundidad mínima legal del dibujo de los neumáticos de una motocicleta?',
    opciones: ['0,5 mm', '1 mm', '1,6 mm', '2 mm'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La profundidad mínima legal del dibujo de los neumáticos es de 1,6 mm. Sin embargo, para motocicletas se recomienda cambiarlos antes de llegar a este mínimo, ya que el dibujo es fundamental para evacuar el agua y mantener la adherencia. Circular con neumáticos desgastados es especialmente peligroso en mojado y constituye infracción en la revisión técnica.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1328,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un motociclista si encuentra grava o arena suelta en la calzada?',
    opciones: ['Frenar bruscamente', 'Reducir velocidad gradualmente, mantener la moto lo más vertical posible y evitar movimientos bruscos', 'Acelerar para pasar rápido', 'Girar el manillar rápidamente para esquivarla'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante grava o arena suelta se debe reducir la velocidad gradualmente sin frenar bruscamente, mantener la motocicleta lo más vertical posible, sujetar firmemente el manillar sin tensarlo y evitar cambios bruscos de dirección. La grava reduce drásticamente la adherencia y cualquier movimiento brusco puede causar una caída.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1329,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe cruzar un motociclista sobre rieles de tren o tranvía?',
    opciones: ['Perpendicularmente o con el mayor ángulo posible respecto al riel', 'Paralelamente al riel', 'No importa el ángulo', 'Acelerando para pasar rápido'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Los rieles deben cruzarse lo más perpendicularmente posible (con un ángulo de al menos 45 grados). Si se cruzan en paralelo o con poco ángulo, la rueda puede quedar atrapada en la ranura del riel causando una caída inmediata. Los rieles son especialmente resbaladizos cuando están mojados.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1330,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué técnica de observación es fundamental para un motociclista en intersecciones?',
    opciones: ['Mirar solo hacia adelante', 'Hacer un barrido visual completo: izquierda, derecha, adelante, espejos y puntos ciegos', 'Confiar en que los demás respetarán las señales', 'Mirar solo los semáforos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En intersecciones, el motociclista debe realizar un barrido visual completo verificando todos los ángulos: izquierda, derecha, adelante, espejos retrovisores y girando la cabeza para verificar puntos ciegos. Muchos accidentes de motocicleta ocurren en intersecciones porque otros conductores no ven al motociclista o no respetan su derecho de paso.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1331,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué es la conducción defensiva aplicada a motocicletas?',
    opciones: ['Conducir agresivamente para imponer respeto', 'Anticipar peligros, asumir que otros no te ven y mantener siempre una ruta de escape', 'Conducir siempre al límite de velocidad', 'Usar la bocina frecuentemente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La conducción defensiva en motocicleta implica anticipar posibles peligros, asumir que otros conductores pueden no verte, mantener siempre una ruta de escape disponible, posicionarse en el carril de forma visible y mantener distancias adecuadas. El motociclista es el usuario más vulnerable del tránsito vehicular y debe extremar precauciones.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1332,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué debe hacer un motociclista cuando un automóvil estacionado tiene a alguien dentro?',
    opciones: ['Pasar lo más cerca posible para ahorrar espacio', 'Alejarse y pasar con precaución anticipando que puede abrirse una puerta', 'Tocar la bocina al pasar', 'No es necesaria ninguna precaución'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El motociclista debe alejarse del vehículo estacionado y pasar con precaución, anticipando que una puerta puede abrirse repentinamente. Este tipo de accidente, conocido como "dooring", es muy frecuente y peligroso para motociclistas y ciclistas. Se recomienda mantener al menos 1,5 metros de distancia lateral de los vehículos estacionados.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1333,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué efecto tiene llevar un pasajero en el comportamiento de la motocicleta?',
    opciones: ['No tiene ningún efecto', 'Aumenta la distancia de frenado, modifica el centro de gravedad y reduce la agilidad', 'Solo afecta la velocidad máxima', 'Mejora la estabilidad en curvas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Llevar un pasajero aumenta significativamente el peso, lo que alarga la distancia de frenado, eleva el centro de gravedad, reduce la capacidad de aceleración y modifica la respuesta en curvas. Se debe ajustar la precarga de la suspensión trasera, conducir más suavemente, frenar antes y tomar las curvas con mayor anticipación.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1334,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la posición correcta del pasajero en una motocicleta?',
    opciones: ['Puede ir sentado de cualquier forma', 'Sentado detrás del conductor, con ambos pies en los estribos y sujetándose al conductor o asideros', 'De lado para mayor comodidad', 'De pie en los estribos traseros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El pasajero debe ir sentado a horcajadas detrás del conductor, con ambos pies apoyados en los estribos traseros, sujetándose firmemente del conductor por la cintura o de los asideros laterales. Debe inclinarse con el conductor en las curvas y evitar movimientos bruscos que desestabilicen la motocicleta.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1335,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Está permitido que dos motocicletas circulen en paralelo en un mismo carril?',
    opciones: ['Sí, siempre está permitido', 'No, cada motocicleta debe ocupar su propio carril completo', 'Solo en vías de baja velocidad', 'Solo si ambos conductores están de acuerdo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las motocicletas deben respetar las mismas normas de circulación que otros vehículos, ocupando un carril completo. Circular en paralelo dentro del mismo carril es peligroso porque reduce el espacio de maniobra, impide reaccionar ante obstáculos y dificulta la visibilidad de otros conductores. Constituye una infracción de tránsito.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1336,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cada cuántos kilómetros se recomienda cambiar el aceite del motor de una motocicleta?',
    opciones: ['Cada 10.000 km', 'Según las especificaciones del fabricante, generalmente entre 3.000 y 6.000 km', 'Solo una vez al año', 'Cuando el motor haga ruidos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El cambio de aceite debe realizarse según las especificaciones del fabricante, que generalmente es entre 3.000 y 6.000 km o al menos una vez al año. El aceite lubrica, enfría y limpia el motor. Un aceite degradado pierde sus propiedades protectoras y puede causar desgaste prematuro del motor y sobrecalentamiento.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1337,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué función cumplen las pastillas de freno en una motocicleta con freno de disco?',
    opciones: ['Enfrían el motor', 'Generan fricción contra el disco para detener la rueda', 'Sostienen la rueda en su lugar', 'Regulan la presión de los neumáticos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las pastillas de freno generan fricción contra el disco de freno cuando se acciona la maneta (delantero) o el pedal (trasero), convirtiendo la energía cinética en calor para desacelerar y detener la rueda. Deben revisarse periódicamente ya que se desgastan con el uso. Pastillas gastadas reducen drásticamente la capacidad de frenado.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1338,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precauciones debe tomar un motociclista al conducir de noche?',
    opciones: ['Las mismas que de día', 'Reducir velocidad, usar ropa reflectante, verificar todas las luces y aumentar la distancia de seguimiento', 'Usar luces altas permanentemente', 'Circular solo por autopistas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'De noche, el motociclista debe reducir la velocidad ya que la visibilidad es menor, usar ropa con elementos reflectantes, verificar que todas las luces funcionen correctamente, aumentar la distancia de seguimiento y extremar la atención ante peatones y obstáculos que pueden ser difíciles de ver. La conducción nocturna multiplica el riesgo para motociclistas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1339,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué es especialmente peligroso el aquaplaning para una motocicleta?',
    opciones: ['No es peligroso para motos', 'Porque con solo dos ruedas, la pérdida de contacto con el suelo significa pérdida total de control', 'Solo es peligroso a altas velocidades', 'Las motos no sufren aquaplaning'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El aquaplaning es cuando una capa de agua se interpone entre el neumático y el asfalto, eliminando toda tracción. Para una motocicleta es especialmente peligroso porque tiene solo dos puntos de contacto con el suelo; si una rueda pierde tracción, se pierde el equilibrio completamente. Se previene reduciendo velocidad y manteniendo neumáticos en buen estado.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1340,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Es obligatorio que las motocicletas lleven las luces encendidas durante el día?',
    opciones: ['No, solo de noche', 'Sí, deben circular siempre con la luz baja encendida', 'Solo fuera de la ciudad', 'Solo en carreteras'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las motocicletas deben circular siempre con la luz baja encendida, tanto de día como de noche. Esta obligación existe porque las luces aumentan significativamente la visibilidad de la motocicleta para los demás usuarios de la vía. La mayoría de las motocicletas modernas encienden la luz automáticamente al arrancar el motor.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1341,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué elementos de iluminación debe tener una motocicleta para circular legalmente?',
    opciones: ['Solo luz delantera y trasera', 'Luz delantera, luz trasera, luz de freno, señaleros y reflectantes', 'Solo luz delantera', 'Las que el conductor considere necesarias'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una motocicleta debe contar con: luz delantera (baja y alta), luz trasera roja, luz de freno, señaleros (intermitentes) delanteros y traseros, y elementos reflectantes. Todas las luces deben funcionar correctamente. La ausencia de alguno de estos elementos no permite aprobar la revisión técnica y constituye una infracción.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1342,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué es el sistema ABS en una motocicleta y cuál es su función?',
    opciones: ['Un sistema de audio integrado', 'Un sistema antibloqueo de frenos que evita que las ruedas se bloqueen al frenar', 'Un sistema de alarma antirrobo', 'Un tipo de suspensión'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El ABS (Sistema Antibloqueo de Frenos) impide que las ruedas se bloqueen durante una frenada intensa, manteniendo la capacidad de dirección. En motocicletas es especialmente importante porque una rueda bloqueada causa pérdida inmediata de estabilidad. El ABS permite frenar con máxima fuerza sin perder el control, reduciendo significativamente los accidentes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1343,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un motociclista si la rueda trasera comienza a derrapar?',
    opciones: ['Frenar con el freno delantero inmediatamente', 'No soltar el embrague bruscamente, mantener la dirección y dejar que la rueda recupere tracción gradualmente', 'Acelerar para estabilizar', 'Saltar de la moto inmediatamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si la rueda trasera derrapa, no se debe frenar con el delantero ni soltar bruscamente los controles. Se debe mantener la dirección, dejar que la rueda trasera recupere tracción gradualmente y reducir la velocidad suavemente. Un derrape trasero controlado es manejable, pero reacciones bruscas pueden convertirlo en una caída.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1344,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe un motociclista negociar un bache o irregularidad en la calzada?',
    opciones: ['Acelerando para saltar sobre él', 'Levantándose ligeramente del asiento, aflojando el agarre del manillar y dejando que la suspensión absorba el impacto', 'Frenando justo antes del bache', 'Girando bruscamente para esquivarlo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante un bache o irregularidad, el motociclista debe levantarse ligeramente del asiento para usar las piernas como amortiguadores adicionales, mantener un agarre firme pero no rígido del manillar para que la dirección se autoajuste, y mantener velocidad constante. Frenar sobre un bache o girar bruscamente para esquivarlo puede causar pérdida de control.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1345,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es el mayor peligro para un motociclista en una intersección?',
    opciones: ['Los semáforos', 'Vehículos que giran a la izquierda sin ver al motociclista que viene de frente', 'Las señales de tránsito', 'Los peatones en la vereda'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El mayor peligro en intersecciones son los vehículos que giran a la izquierda sin percibir al motociclista que se aproxima de frente. Muchos conductores subestiman la velocidad de la motocicleta o simplemente no la ven por su tamaño reducido. El motociclista debe reducir velocidad al acercarse a intersecciones y estar preparado para frenar o esquivar.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1346,
    categoria: 'Conducción Segura',
    pregunta: '¿Es recomendable usar el freno motor en una motocicleta?',
    opciones: ['No, daña el motor', 'Sí, es útil para reducir velocidad gradualmente sin desgastar los frenos', 'Solo en pendientes descendentes', 'Nunca se debe usar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El freno motor es muy útil para reducir velocidad gradualmente, complementando los frenos convencionales. Se activa bajando marchas progresivamente. Es especialmente útil en descensos prolongados donde los frenos podrían sobrecalentarse, y en condiciones de piso resbaladizo donde la desaceleración suave es más segura que frenar con las manetas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1347,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué edad mínima se requiere para obtener la licencia clase C para motocicletas en Chile?',
    opciones: ['16 años', '17 años', '18 años', '21 años'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La edad mínima para obtener la licencia clase C para motocicletas es de 18 años. Se requiere aprobar un examen teórico específico sobre conducción de motocicletas, un examen práctico de manejo y un examen psicotécnico. Además, se debe contar con un certificado de una escuela de conducción autorizada.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1348,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puede una motocicleta circular por ciclovías en Chile?',
    opciones: ['Sí, son vehículos de dos ruedas', 'No, las ciclovías son exclusivas para bicicletas y ciclos no motorizados', 'Solo las motocicletas eléctricas', 'Solo si la cilindrada es menor a 50 cc'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las ciclovías están destinadas exclusivamente a bicicletas y ciclos no motorizados. Las motocicletas, independientemente de su cilindrada, no pueden circular por ciclovías. Hacerlo constituye una infracción de tránsito y pone en riesgo a los ciclistas. Las motocicletas deben circular por la calzada vehicular.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1349,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué función cumple el embrague en una motocicleta con transmisión manual?',
    opciones: ['Frena la rueda trasera', 'Conecta y desconecta la transmisión del motor a la rueda trasera para cambiar de marcha', 'Regula el combustible', 'Activa las luces'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El embrague conecta y desconecta la potencia del motor de la transmisión, permitiendo cambiar de marcha suavemente. Se acciona con la maneta izquierda. Un uso incorrecto del embrague puede causar tirones, calados del motor o desgaste prematuro de los discos. El dominio del embrague es fundamental para una conducción suave y segura.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1350,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué tipo de combustible usan la mayoría de las motocicletas?',
    opciones: ['Diésel', 'Gasolina (bencina) del octanaje recomendado por el fabricante', 'Gas natural', 'Cualquier tipo de combustible'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La mayoría de las motocicletas usan gasolina (bencina) del octanaje especificado por el fabricante, generalmente 93 o 95 octanos. Usar un octanaje inferior puede causar detonación prematura que daña el motor. Las motocicletas no usan diésel. Es importante seguir las recomendaciones del manual del propietario.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1351,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué debe hacer un motociclista ante un vehículo que cambia de carril sin señalizar?',
    opciones: ['Adelantarlo por la derecha', 'Reducir velocidad, mantener distancia y buscar una ruta de escape', 'Acercarse y tocar la bocina', 'Acelerar para pasarlo antes de que complete la maniobra'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante un vehículo que cambia de carril sin señalizar, el motociclista debe reducir velocidad inmediatamente, mantener distancia de seguridad y buscar una ruta de escape alternativa. No se debe intentar adelantar ni acercarse. Este tipo de situación es predecible si se observan señales como las ruedas del vehículo que se dirigen hacia el otro carril.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1352,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo debe adelantar un motociclista a otro vehículo de forma segura?',
    opciones: ['Por el lado que sea más conveniente', 'Verificar espejos y punto ciego, señalizar, adelantar por la izquierda con margen lateral y regresar al carril', 'Acelerar al máximo y pasar rápido', 'Tocar la bocina antes de adelantar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para adelantar de forma segura: verificar espejos retrovisores, girar brevemente la cabeza para verificar el punto ciego, señalizar con el intermitente izquierdo, adelantar por la izquierda manteniendo un margen lateral seguro, y regresar al carril derecho cuando se vea el vehículo adelantado en el espejo. Nunca adelantar en curvas o zonas de poca visibilidad.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1353,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precaución debe tomar un motociclista al pasar sobre pintura vial (líneas de demarcación)?',
    opciones: ['Ninguna precaución especial', 'Mantener la moto vertical y evitar frenar o acelerar sobre la pintura', 'Acelerar para pasar rápido', 'Frenar antes de la pintura'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La pintura vial (líneas de demarcación, flechas, cruces peatonales) es significativamente más resbaladiza que el asfalto, especialmente cuando está mojada. El motociclista debe mantener la moto lo más vertical posible al pasar sobre pintura y evitar frenar, acelerar o hacer maniobras bruscas sobre ella para prevenir deslizamientos.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1354,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué indica un líquido aceitoso debajo de la motocicleta estacionada?',
    opciones: ['Es normal, todas las motos gotean', 'Puede indicar una fuga de aceite, líquido de frenos o refrigerante que debe revisarse urgentemente', 'Solo es agua de condensación', 'Es combustible evaporándose'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un líquido aceitoso debajo de la motocicleta puede indicar fugas de aceite del motor, líquido de frenos o refrigerante, todas situaciones que requieren atención inmediata. Una fuga de aceite puede causar sobrecalentamiento del motor, una fuga de líquido de frenos compromete la capacidad de frenado, y ambas son extremadamente peligrosas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1355,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué efecto tiene la fatiga en la conducción de motocicleta?',
    opciones: ['No afecta a los motociclistas experimentados', 'Reduce los tiempos de reacción, la concentración y el equilibrio, aumentando el riesgo de accidente', 'Solo afecta en viajes largos de más de 8 horas', 'Mejora los reflejos por la adrenalina'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La fatiga es especialmente peligrosa en motocicleta porque además de reducir tiempos de reacción y concentración como en cualquier vehículo, afecta el equilibrio y la coordinación necesarios para mantener la moto estable. Se recomienda descansar cada 1-2 horas en viajes largos, hidratarse y no conducir con sueño.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1356,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo se debe estacionar correctamente una motocicleta?',
    opciones: ['En cualquier lugar disponible en la vereda', 'En estacionamientos habilitados, usando el caballete o pata lateral sobre superficie firme', 'Sobre la línea de la cuneta', 'Atada a postes de señalización'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La motocicleta debe estacionarse en lugares habilitados, usando el caballete central o la pata lateral sobre superficie firme y plana. En superficies blandas o calientes (asfalto en verano) la pata puede hundirse. Se debe dejar la dirección bloqueada, el interruptor de corte activado y, si es posible, un candado o cadena de seguridad adicional.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1357,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué es el efecto SMIDSY y cómo afecta a los motociclistas?',
    opciones: ['Es un tipo de neumático', 'Es la tendencia de otros conductores a no ver motocicletas ("Sorry Mate, I Didn\'t See You")', 'Es un sistema de frenos', 'Es una técnica de conducción'],
    respuestaCorrecta: 1,
    explicacionTexto: 'SMIDSY ("Sorry Mate, I Didn\'t See You" - "Perdona, no te vi") describe la tendencia de conductores de automóviles a no percibir motocicletas en el tránsito. Se debe a que el cerebro tiende a buscar amenazas grandes (autos, camiones) y puede "filtrar" objetos pequeños como motos. El motociclista debe conducir asumiendo que los demás no lo ven.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1358,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué función cumple la suspensión en una motocicleta?',
    opciones: ['Solo proporcionar comodidad', 'Absorber irregularidades del terreno, mantener el contacto de los neumáticos con el suelo y proporcionar estabilidad', 'Frenar la motocicleta', 'Regular la velocidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La suspensión absorbe las irregularidades del terreno, mantiene los neumáticos en contacto con el suelo para garantizar tracción y frenado, y proporciona estabilidad direccional. Una suspensión en mal estado o mal regulada afecta gravemente la seguridad: el neumático pierde contacto con el suelo en baches, reduciendo adherencia y control.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_c'],
  },
  {
    id: 1359,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un motociclista si se pincha un neumático mientras conduce?',
    opciones: ['Frenar bruscamente', 'Sujetar firme el manillar, reducir velocidad gradualmente sin frenar bruscamente y orillarse a un lugar seguro', 'Acelerar para llegar rápido a un taller', 'Soltar el manillar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si se pincha un neumático, se debe sujetar firmemente el manillar sin tensarlo en exceso, reducir velocidad gradualmente sin frenar bruscamente (especialmente si es la rueda delantera), señalizar y orillarse a un lugar seguro fuera de la calzada. Un pinchazo trasero es más manejable; uno delantero requiere mayor cuidado para no perder la dirección.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_c'],
  },
];
