import type { Question } from './questionsData';

export const questionsClaseD: Question[] = [
  {
    id: 1400,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué tipo de licencia se requiere para operar maquinaria automotriz en vías públicas en Chile?',
    opciones: ['Clase B', 'Clase C', 'Clase D', 'Clase E'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La licencia Clase D habilita para operar maquinaria automotriz como tractores, retroexcavadoras, grúas y otros equipos especiales que circulan por vías públicas. El postulante debe cumplir requisitos específicos de edad, salud y aprobar exámenes teóricos y prácticos especializados.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1401,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima permitida para maquinaria agrícola circulando por caminos públicos?',
    opciones: ['20 km/h', '30 km/h', '40 km/h', '50 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La maquinaria agrícola y automotriz tiene una velocidad máxima de 30 km/h al circular por caminos públicos, debido a sus limitaciones de frenado, maniobrabilidad y estabilidad. Deben circular por la pista derecha y facilitar el adelantamiento de otros vehículos cuando sea seguro.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1402,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué señalización debe llevar la maquinaria automotriz al circular por vías públicas de noche?',
    opciones: ['Solo luces delanteras', 'Luces delanteras, traseras, de posición y dispositivos reflectantes', 'Solo balizas amarillas', 'No requiere señalización especial'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La maquinaria automotriz debe circular con luces delanteras, traseras, de posición y dispositivos reflectantes visibles desde ambos lados. Las luces permiten que otros conductores identifiquen la presencia y dimensiones de la maquinaria, especialmente de noche cuando su baja velocidad representa un riesgo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1403,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué función cumple la baliza giratoria amarilla en la maquinaria automotriz?',
    opciones: ['Indica que la máquina está apagada', 'Advierte a otros usuarios de la vía sobre la presencia de un vehículo lento o de dimensiones especiales', 'Señala una emergencia mecánica', 'Es decorativa y no tiene función legal'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La baliza giratoria amarilla alerta a los demás usuarios de la vía sobre la presencia de maquinaria lenta o de dimensiones especiales. Debe estar encendida siempre que la maquinaria circule por vías públicas, tanto de día como de noche, para prevenir colisiones por alcance u otros accidentes.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1404,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el principal riesgo al operar una retroexcavadora en una pendiente lateral?',
    opciones: ['Desgaste excesivo de neumáticos', 'Volcamiento por desplazamiento del centro de gravedad', 'Recalentamiento del motor', 'Pérdida de presión hidráulica'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El volcamiento es el riesgo principal al operar maquinaria en pendientes laterales. El centro de gravedad alto de la retroexcavadora, combinado con la inclinación del terreno, puede provocar que la máquina pierda estabilidad y vuelque. Se debe evitar operar en pendientes superiores a las especificadas por el fabricante.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1405,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué se debe hacer antes de iniciar la operación de cualquier maquinaria pesada?',
    opciones: ['Arrancar inmediatamente para calentar el motor', 'Realizar una inspección visual completa alrededor de la máquina', 'Solo verificar el combustible', 'Encender la radio para comunicarse'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de operar cualquier maquinaria pesada, se debe realizar una inspección visual completa que incluya verificar el estado de neumáticos u orugas, niveles de fluidos, funcionamiento de luces y bocina, estado del sistema hidráulico, y asegurarse de que no haya personas u obstáculos alrededor de la máquina.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1406,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la posición correcta del balde de una cargadora frontal al desplazarse por una vía?',
    opciones: ['Elevado al máximo para mejor visibilidad', 'A nivel del suelo para mayor estabilidad', 'A una altura intermedia de 30 a 40 cm del suelo', 'No importa la posición del balde'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Al desplazarse por una vía, el balde de la cargadora frontal debe mantenerse a una altura intermedia de aproximadamente 30 a 40 cm del suelo. Esta posición reduce la obstrucción de la visión del operador y mantiene un centro de gravedad bajo, mejorando la estabilidad de la máquina durante el traslado.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1407,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué sistema permite el movimiento del brazo y la pala de una excavadora?',
    opciones: ['Sistema eléctrico', 'Sistema hidráulico', 'Sistema neumático', 'Sistema mecánico por cables'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El sistema hidráulico es el responsable del movimiento del brazo, la pala, la rotación de la torreta y otras funciones de la excavadora. Funciona mediante aceite a presión que acciona cilindros y motores hidráulicos. Es fundamental mantener los niveles de aceite hidráulico y revisar mangueras para prevenir fugas y fallas.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1408,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué precauciones debe tomar el operador de maquinaria al acercarse a tendidos eléctricos aéreos?',
    opciones: ['Ninguna, si la máquina tiene neumáticos de goma', 'Mantener una distancia mínima de seguridad de al menos 3 metros de los cables', 'Solo apagar el motor', 'Acelerar para pasar rápido bajo los cables'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se debe mantener una distancia mínima de al menos 3 metros de los tendidos eléctricos aéreos, incluyendo el brazo, la pala y cualquier parte elevada de la maquinaria. El contacto con líneas eléctricas puede provocar electrocución fatal. Antes de trabajar cerca de líneas de alta tensión, se debe coordinar con la empresa eléctrica.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1409,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Está permitido transportar pasajeros en la cabina de maquinaria automotriz diseñada para un solo operador?',
    opciones: ['Sí, si hay espacio disponible', 'No, solo debe ir el operador autorizado', 'Sí, si es un tramo corto', 'Solo durante emergencias'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Está prohibido transportar pasajeros en la cabina de maquinaria diseñada para un solo operador. La presencia de personas adicionales puede interferir con los controles, reducir la visibilidad y aumentar el riesgo de accidentes. Solo el operador autorizado con licencia Clase D vigente puede ocupar la cabina.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1410,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué se debe hacer al estacionar una excavadora al final de la jornada de trabajo?',
    opciones: ['Dejar el brazo extendido hacia arriba', 'Apoyar el balde en el suelo, apagar el motor y retirar la llave', 'Solo apagar el motor', 'Dejar el motor en ralentí toda la noche'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al estacionar una excavadora, se debe apoyar el balde en el suelo para evitar movimientos involuntarios, activar el freno de estacionamiento, apagar el motor y retirar la llave de contacto. Además, se deben colocar calzas si la máquina está en pendiente y señalizar su ubicación si está en una vía pública.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1411,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál es la función del sistema de orugas en maquinaria pesada?',
    opciones: ['Aumentar la velocidad de desplazamiento', 'Distribuir el peso de la máquina sobre una superficie mayor para mejorar la tracción y reducir la presión sobre el suelo', 'Reducir el consumo de combustible', 'Facilitar el giro en esquinas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las orugas distribuyen el peso de la maquinaria sobre una superficie mayor que los neumáticos, lo que reduce la presión sobre el terreno y mejora la tracción en suelos blandos, húmedos o irregulares. Sin embargo, las orugas metálicas pueden dañar el pavimento, por lo que su circulación por calles asfaltadas está restringida.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1412,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puede una maquinaria con orugas metálicas circular libremente por calles pavimentadas?',
    opciones: ['Sí, sin restricciones', 'No, debe transportarse en un camión plataforma para no dañar el pavimento', 'Solo en horario nocturno', 'Solo si la calle es de hormigón'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La maquinaria con orugas metálicas no puede circular directamente por calles pavimentadas porque daña la superficie del asfalto. Debe ser transportada en camiones plataforma o cama baja hasta el lugar de trabajo. Solo la maquinaria con orugas de goma puede desplazarse por pavimento sin causar daños significativos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1413,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es la principal causa de accidentes fatales con maquinaria pesada en zonas de construcción?',
    opciones: ['Fallas mecánicas del motor', 'Atropello de trabajadores por puntos ciegos de la maquinaria', 'Exceso de velocidad', 'Condiciones climáticas adversas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los atropellos de trabajadores en zonas de construcción son la principal causa de accidentes fatales con maquinaria pesada, debido a los amplios puntos ciegos que tienen estos equipos. El operador debe verificar siempre que el área esté despejada antes de mover la máquina y utilizar señaleros cuando la visibilidad sea limitada.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1414,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es un señalero o banderero en el contexto de operaciones con maquinaria?',
    opciones: ['Un dispositivo electrónico de la máquina', 'Una persona capacitada que guía al operador con señales manuales en zonas de visibilidad reducida', 'Un tipo de señal de tránsito', 'Un sensor automático de proximidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El señalero o banderero es una persona capacitada que se ubica fuera de la maquinaria y guía al operador mediante señales manuales estandarizadas. Su función es crítica en maniobras de retroceso, carga y descarga, y operaciones en zonas con trabajadores o público. Debe usar chaleco reflectante y ubicarse siempre visible para el operador.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1415,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué se debe verificar en el sistema hidráulico antes de operar la maquinaria?',
    opciones: ['Solo el color del aceite', 'Nivel de aceite hidráulico, estado de mangueras, conexiones y ausencia de fugas', 'Solo la presión del sistema', 'No requiere verificación diaria'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de operar, se debe verificar el nivel de aceite hidráulico, inspeccionar visualmente todas las mangueras en busca de desgaste, grietas o abultamientos, revisar las conexiones y verificar que no existan fugas. Una falla hidráulica puede provocar la caída súbita del brazo o la pala, con graves consecuencias.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1416,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué elementos de protección personal son obligatorios para el operador de maquinaria pesada?',
    opciones: ['Solo casco', 'Casco, calzado de seguridad, chaleco reflectante y protección auditiva según el equipo', 'Solo guantes y lentes', 'No se requiere equipo especial dentro de la cabina'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El operador de maquinaria pesada debe usar casco de seguridad, calzado con punta de acero, chaleco reflectante de alta visibilidad y protección auditiva cuando el nivel de ruido lo requiera. Además, debe usar cinturón de seguridad dentro de la cabina para protegerse en caso de volcamiento.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1417,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué debe hacer el operador si detecta una fuga de aceite hidráulico durante la operación?',
    opciones: ['Continuar trabajando y reportar al final del turno', 'Detener inmediatamente la operación, apagar la máquina y reportar la fuga', 'Intentar reparar la fuga con la máquina en funcionamiento', 'Agregar más aceite y seguir operando'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante una fuga de aceite hidráulico, se debe detener inmediatamente la operación y apagar la máquina. El aceite hidráulico a presión puede causar quemaduras graves y lesiones por inyección subcutánea. Además, la pérdida de presión puede provocar la caída de implementos elevados. Nunca intente tocar o reparar una fuga con el sistema presurizado.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1418,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué documentación debe portar el operador de maquinaria automotriz al circular por vías públicas?',
    opciones: ['Solo la licencia de conducir', 'Licencia Clase D, permiso de circulación de la maquinaria, SOAP y revisión técnica', 'Solo el certificado del operador', 'No requiere documentación si es dentro de una obra'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al circular por vías públicas, el operador debe portar su licencia Clase D vigente, el permiso de circulación de la maquinaria, el SOAP y la revisión técnica al día. La falta de cualquiera de estos documentos puede resultar en multas y la retención de la maquinaria por parte de Carabineros.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1419,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la manera correcta de descender una pendiente pronunciada con un tractor?',
    opciones: ['En punto muerto para ahorrar combustible', 'Con una marcha baja engranada, usando el freno motor y sin desembragar', 'Frenando continuamente con el pedal de freno', 'En reversa para mayor control'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al descender pendientes con un tractor, se debe seleccionar una marcha baja y utilizar el freno motor como asistencia principal. Nunca se debe bajar en punto muerto ni desembragar, ya que se pierde el freno motor. El frenado continuo puede recalentar los frenos y provocar su falla total, conocida como fading.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1420,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué función cumple el contrapeso trasero en una excavadora?',
    opciones: ['Proteger el motor', 'Equilibrar el peso de la carga en el brazo delantero para evitar el volcamiento hacia adelante', 'Mejorar la velocidad de desplazamiento', 'Almacenar combustible adicional'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El contrapeso trasero de la excavadora equilibra el peso de la carga elevada por el brazo delantero, manteniendo la estabilidad de la máquina durante las operaciones de excavación y elevación. Sin el contrapeso adecuado, la máquina se inclinaría hacia adelante al levantar cargas, aumentando el riesgo de volcamiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1421,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué zona de peligro se genera al girar la torreta superior de una excavadora?',
    opciones: ['Solo la zona frontal', 'Un área circular completa alrededor de la máquina correspondiente al radio de giro del brazo y contrapeso', 'Solo la zona trasera', 'No genera zonas de peligro si gira lento'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al girar la torreta, se genera una zona de peligro circular alrededor de la excavadora que abarca el radio de giro del brazo y el contrapeso trasero. Cualquier persona u objeto dentro de este radio puede ser golpeado. El operador debe verificar que el área esté completamente despejada antes de realizar cualquier giro.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1422,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué es peligroso subir o bajar de la maquinaria mientras está en movimiento?',
    opciones: ['Porque se gasta más combustible', 'Porque existe riesgo de caída, atrapamiento o ser arrollado por la propia máquina', 'Porque se desgastan los escalones', 'No es peligroso si se hace con cuidado'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Subir o bajar de maquinaria en movimiento es extremadamente peligroso. El operador puede resbalar, caer y quedar atrapado bajo las orugas o neumáticos. Siempre se debe esperar a que la máquina esté completamente detenida, utilizar los tres puntos de apoyo al subir o bajar y mantener los escalones limpios de barro o grasa.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1423,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué restricción horaria puede aplicarse a la circulación de maquinaria pesada por vías urbanas?',
    opciones: ['No existe restricción horaria', 'Las municipalidades pueden restringir la circulación a horarios fuera de punta', 'Solo puede circular de noche', 'Solo puede circular los fines de semana'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las municipalidades tienen la facultad de restringir la circulación de maquinaria pesada en vías urbanas durante horarios punta para evitar congestión y riesgos. Generalmente se permite la circulación en horarios nocturnos o de baja demanda vehicular. El operador debe conocer las ordenanzas locales antes de transitar por zonas urbanas.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1424,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué indica una temperatura excesivamente alta en el indicador del sistema hidráulico?',
    opciones: ['Funcionamiento normal bajo carga', 'Posible falla en el sistema de enfriamiento, bajo nivel de aceite o filtro obstruido', 'Que el motor está en óptimas condiciones', 'Que se debe acelerar más para enfriar el sistema'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una temperatura excesiva en el sistema hidráulico puede indicar bajo nivel de aceite, filtro obstruido, falla en el radiador de aceite o sobrecarga del sistema. Se debe detener la operación y dejar enfriar la máquina. Operar con el sistema recalentado degrada el aceite, daña sellos y puede provocar fallas catastróficas.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1425,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el procedimiento correcto si una grúa móvil comienza a inclinarse al levantar una carga?',
    opciones: ['Subir la carga rápidamente para completar la maniobra', 'Descender la carga inmediatamente de forma controlada y reposicionar los apoyos estabilizadores', 'Girar la torreta para equilibrar', 'Acelerar el motor para más potencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si la grúa comienza a inclinarse, se debe descender la carga de inmediato de forma controlada. Intentar completar la maniobra puede provocar un volcamiento total. Luego se debe verificar que los estabilizadores estén correctamente extendidos y apoyados, y recalcular si la carga excede la capacidad de la tabla de cargas de la grúa.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1426,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué son los estabilizadores o gatos hidráulicos en una grúa móvil?',
    opciones: ['Amortiguadores del chasis', 'Apoyos extensibles que se despliegan para ampliar la base de sustentación y dar estabilidad durante las operaciones de izaje', 'Frenos de emergencia', 'Elevadores para mantenimiento'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los estabilizadores son apoyos hidráulicos extensibles que se despliegan antes de operar la grúa. Amplían la base de sustentación de la máquina, distribuyendo el peso y evitando el volcamiento al levantar cargas. Deben apoyarse sobre terreno firme o placas de apoyo y estar completamente extendidos según las instrucciones del fabricante.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1427,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué riesgo existe al operar maquinaria pesada cerca de excavaciones o zanjas?',
    opciones: ['Solo riesgo de ensuciar la máquina', 'Colapso del borde de la excavación por el peso de la maquinaria, provocando la caída de la máquina a la zanja', 'Ningún riesgo si se opera lentamente', 'Solo riesgo de dañar las tuberías subterráneas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El peso de la maquinaria puede provocar el colapso del borde de una excavación, causando que la máquina caiga a la zanja. Se debe mantener una distancia de seguridad del borde equivalente a la profundidad de la excavación. El terreno cercano a zanjas es inestable y puede ceder sin aviso previo.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1428,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué obligación tiene el operador de maquinaria respecto a la señalización de zonas de trabajo en vías públicas?',
    opciones: ['No tiene obligación, es responsabilidad del municipio', 'Debe asegurar la correcta señalización con conos, barreras y señales de advertencia antes de iniciar trabajos', 'Solo debe encender la baliza de la máquina', 'Debe avisar verbalmente a los peatones'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de iniciar trabajos en vías públicas, se debe instalar señalización temporal que incluya conos, barreras, señales de advertencia de obras y, cuando corresponda, semáforos provisionales o personal de control de tránsito. La señalización debe ser visible de día y de noche, y debe retirarse al finalizar los trabajos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1429,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué tipo de motor utilizan la mayoría de las maquinarias pesadas de construcción?',
    opciones: ['Motor a gasolina', 'Motor diésel', 'Motor eléctrico', 'Motor a gas natural'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La mayoría de las maquinarias pesadas utilizan motores diésel por su mayor torque a bajas revoluciones, mayor eficiencia energética, mayor durabilidad bajo cargas pesadas y menor riesgo de incendio comparado con motores a gasolina. Los motores diésel también requieren un mantenimiento riguroso de filtros de combustible y aire.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1430,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer el operador antes de retroceder con maquinaria pesada?',
    opciones: ['Solo mirar por los espejos retrovisores', 'Verificar que el área trasera esté despejada, usar señalero si es necesario y activar la alarma de retroceso', 'Tocar la bocina una vez', 'Retroceder lentamente sin verificación previa'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de retroceder, el operador debe verificar personalmente que el área trasera esté despejada o contar con un señalero. La alarma de retroceso debe estar operativa y funcionando. Los espejos solos no son suficientes debido a los amplios puntos ciegos de la maquinaria. La mayoría de atropellos ocurren durante maniobras de retroceso.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1431,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es el riesgo principal al operar un tractor agrícola con implementos enganchados en vías públicas?',
    opciones: ['Mayor consumo de combustible', 'Los implementos pueden sobresalir del ancho del tractor y golpear vehículos, postes o peatones', 'Desgaste acelerado del embrague', 'Vibración excesiva en la cabina'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los implementos agrícolas enganchados al tractor pueden sobresalir significativamente del ancho del vehículo, representando un peligro para vehículos que adelantan, postes, señales y peatones. El operador debe conocer las dimensiones totales del conjunto, señalizar los extremos salientes y circular con precaución extrema en vías estrechas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1432,
    categoria: 'Mecánica Básica',
    pregunta: '¿Con qué frecuencia se deben engrasar los puntos de lubricación de una excavadora?',
    opciones: ['Una vez al mes', 'Diariamente o según las horas de operación indicadas por el fabricante', 'Solo cuando haya ruidos extraños', 'Cada 500 horas de operación'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los puntos de lubricación de una excavadora deben engrasarse diariamente o según las horas de operación que indique el manual del fabricante. La falta de lubricación provoca desgaste acelerado de pasadores, bujes y articulaciones, generando juego excesivo, menor precisión en los movimientos y costosas reparaciones.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1433,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precaución especial se debe tomar al operar maquinaria en terrenos con presencia de gas o combustibles?',
    opciones: ['Operar normalmente con las ventanas cerradas', 'Verificar la ausencia de fugas de gas, mantener extintores disponibles y evitar generar chispas', 'Solo usar mascarilla', 'Acelerar para salir rápido de la zona'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En terrenos con presencia de gas o combustibles, se debe verificar la ausencia de fugas, tener extintores adecuados disponibles, evitar generar chispas y contar con procedimientos de evacuación. La maquinaria diésel puede funcionar en estas zonas con precauciones, pero se deben seguir estrictamente los protocolos de seguridad del lugar.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1434,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué edad mínima se requiere para obtener la licencia Clase D en Chile?',
    opciones: ['16 años', '18 años', '20 años', '21 años'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para obtener la licencia Clase D se requiere tener al menos 18 años de edad. Además, se debe aprobar un examen teórico sobre normativa de tránsito aplicable a maquinaria, un examen práctico de operación y un examen psicotécnico que evalúe aptitudes visuales, auditivas y psicomotoras.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1435,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el riesgo de operar una grúa con viento fuerte?',
    opciones: ['Solo incomodidad para el operador', 'La carga suspendida puede oscilar descontroladamente y la grúa puede perder estabilidad', 'Mayor eficiencia por enfriamiento del motor', 'No existe riesgo significativo con viento'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El viento fuerte puede hacer oscilar la carga suspendida de forma impredecible, dificultar su posicionamiento y generar fuerzas laterales que comprometan la estabilidad de la grúa. Las operaciones de izaje deben suspenderse cuando la velocidad del viento supere los límites establecidos por el fabricante de la grúa.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1436,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué indica el manómetro de presión de aceite del motor en la cabina de la maquinaria?',
    opciones: ['La temperatura del refrigerante', 'La presión de lubricación del motor, que debe mantenerse dentro del rango normal', 'El nivel de combustible', 'La presión de los neumáticos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El manómetro de presión de aceite indica si el motor está siendo lubricado correctamente. Una presión baja puede significar falta de aceite, bomba defectuosa o filtro obstruido. Si la presión cae por debajo del rango normal, se debe detener el motor inmediatamente para evitar daños graves por falta de lubricación.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1437,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué se debe considerar al trasladar maquinaria pesada en un camión cama baja por carreteras?',
    opciones: ['Solo el peso total del conjunto', 'Peso total, altura del conjunto, ancho de la carga, permisos de transporte especial y ruta autorizada', 'Solo la distancia del traslado', 'No se requiere consideración especial'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al transportar maquinaria en camión cama baja se debe considerar el peso total del conjunto para no exceder los límites de la vía, la altura para pasar bajo puentes y cables, el ancho para respetar los gálibos, y obtener permisos de transporte especial si se exceden dimensiones normales. La carga debe estar correctamente amarrada y señalizada.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1438,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué se debe hacer si la maquinaria queda atrapada en terreno blando o lodoso?',
    opciones: ['Acelerar al máximo para salir', 'No forzar la máquina, solicitar asistencia de otra maquinaria y evaluar opciones de rescate seguro', 'Balancear la máquina adelante y atrás rápidamente', 'Abandonar la máquina y volver al día siguiente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si la maquinaria queda atrapada en terreno blando, no se debe forzar acelerando ya que esto hunde más la máquina. Se debe solicitar asistencia de otra maquinaria con capacidad de tracción adecuada, colocar tablones o material sólido bajo las orugas o neumáticos, y planificar la maniobra de rescate de forma segura.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1439,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué responsabilidad tiene el operador si la maquinaria causa daños al pavimento o infraestructura pública?',
    opciones: ['Ninguna, es responsabilidad del contratista', 'El operador y la empresa son responsables de los daños causados y deben asumir la reparación', 'Solo responsabilidad si actuó con negligencia comprobada', 'La municipalidad asume los costos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El operador y la empresa propietaria de la maquinaria son responsables solidariamente por los daños causados a pavimentos, veredas, señalización u otra infraestructura pública. Deben reparar o indemnizar los daños. Por esto es importante contar con seguros de responsabilidad civil y operar con las precauciones necesarias.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1440,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la importancia del cinturón de seguridad dentro de la cabina de maquinaria pesada?',
    opciones: ['No es necesario porque la cabina es reforzada', 'Evita que el operador sea expulsado de la cabina en caso de volcamiento, protegiéndolo dentro de la estructura ROPS', 'Solo es obligatorio en carretera', 'Es opcional según el tipo de maquinaria'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El cinturón de seguridad mantiene al operador dentro de la cabina protegida por la estructura ROPS (Roll Over Protective Structure) en caso de volcamiento. Sin cinturón, el operador puede ser expulsado y quedar atrapado bajo la máquina. Estadísticamente, la mayoría de las muertes por volcamiento ocurren cuando el operador no usa cinturón.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1441,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué es la estructura ROPS en maquinaria pesada?',
    opciones: ['Un sistema de navegación GPS', 'Una estructura de protección contra volcamiento que protege al operador dentro de la cabina', 'Un tipo de suspensión hidráulica', 'Un sistema de control remoto'],
    respuestaCorrecta: 1,
    explicacionTexto: 'ROPS significa Roll Over Protective Structure (Estructura de Protección contra Volcamiento). Es una estructura reforzada, generalmente integrada en la cabina, diseñada para mantener un espacio de supervivencia para el operador en caso de volcamiento. Es obligatoria en la mayoría de las maquinarias pesadas y no debe modificarse.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1442,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué precauciones debe tomar el operador al cruzar un puente con maquinaria pesada?',
    opciones: ['Cruzar a máxima velocidad para reducir el tiempo sobre el puente', 'Verificar la capacidad de carga del puente, respetar el peso máximo señalizado y cruzar lentamente por el centro', 'No se requieren precauciones especiales', 'Solo verificar que no venga otro vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de cruzar un puente, el operador debe verificar que el peso de la maquinaria no exceda la capacidad de carga indicada en la señalización del puente. Se debe cruzar lentamente, por el centro de la calzada si es posible, y sin detenerse sobre la estructura. Exceder el peso máximo puede provocar el colapso del puente.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1443,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer el operador al trabajar con maquinaria cerca de redes de servicios subterráneos (agua, gas, electricidad)?',
    opciones: ['Excavar directamente ya que la máquina es resistente', 'Solicitar planos de redes, realizar cateos manuales previos y excavar con precaución extrema', 'Solo excavar hasta 50 cm de profundidad', 'Ignorar las redes si no están señalizadas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de excavar, se deben solicitar los planos de redes subterráneas a las empresas de servicios, realizar cateos manuales para ubicar las instalaciones y mantener distancias de seguridad. Dañar una red de gas puede causar explosiones, una red eléctrica subterránea puede provocar electrocución, y dañar redes de agua genera inundaciones.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1444,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué tipo de seguro adicional es recomendable para la operación de maquinaria pesada?',
    opciones: ['Solo el SOAP es suficiente', 'Seguro de responsabilidad civil por daños a terceros y seguro de maquinaria', 'Seguro de vida del operador', 'No se requieren seguros adicionales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Además del SOAP obligatorio, es recomendable contar con un seguro de responsabilidad civil que cubra daños a terceros y un seguro de maquinaria que cubra daños al equipo. La operación de maquinaria pesada implica riesgos significativos de causar daños materiales y personales cuyas indemnizaciones pueden ser muy elevadas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1445,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el procedimiento correcto al cargar combustible en maquinaria pesada?',
    opciones: ['Cargar con el motor encendido para no perder tiempo', 'Apagar el motor, no fumar, conectar cable a tierra y usar recipientes aprobados', 'Solo apagar el motor', 'No hay procedimiento especial para maquinaria diésel'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al cargar combustible se debe apagar el motor, prohibir fumar y cualquier fuente de ignición, conectar el cable a tierra para evitar descargas de electricidad estática, y utilizar recipientes y bombas aprobadas. Aunque el diésel es menos inflamable que la gasolina, sus vapores pueden encenderse bajo ciertas condiciones.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1446,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué componente protege al operador de objetos que caen sobre la cabina?',
    opciones: ['El parabrisas reforzado', 'La estructura FOPS (Falling Object Protective Structure)', 'El techo solar', 'La visera del techo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La estructura FOPS (Falling Object Protective Structure) es una protección en el techo de la cabina diseñada para resistir el impacto de objetos que caen, como rocas, troncos o material de demolición. Es especialmente importante en operaciones de minería, demolición y carga de materiales. No debe modificarse ni retirarse.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1447,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué factor determina la capacidad máxima de carga que puede levantar una grúa?',
    opciones: ['Solo el peso de la carga', 'La combinación del peso de la carga, el radio de operación y la altura de elevación según la tabla de cargas del fabricante', 'Solo la potencia del motor', 'El tipo de cable utilizado'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La capacidad de una grúa depende de la interacción entre el peso de la carga, el radio de operación (distancia horizontal) y la altura de elevación. La tabla de cargas del fabricante indica la capacidad máxima para cada combinación. Exceder estos límites compromete la estabilidad y puede provocar el volcamiento de la grúa.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1448,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe verificar el operador en los neumáticos de un tractor antes de circular por caminos públicos?',
    opciones: ['Solo que estén inflados', 'Presión adecuada, profundidad del dibujo, ausencia de cortes o deformaciones y ajuste de tuercas', 'Solo el tamaño de los neumáticos', 'No requieren inspección especial'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los neumáticos del tractor deben inspeccionarse verificando la presión correcta según el manual, la profundidad del dibujo para garantizar tracción, la ausencia de cortes, grietas o deformaciones, y el correcto ajuste de las tuercas de las ruedas. Neumáticos en mal estado comprometen la estabilidad y el frenado de la maquinaria.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_d'],
  },
  {
    id: 1449,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sanción puede recibir un operador que causa un accidente por operar maquinaria sin la licencia correspondiente?',
    opciones: ['Solo multa de tránsito', 'Responsabilidad penal por cuasidelito, multas y posible presidio si hay lesiones o muerte', 'Suspensión de licencia por 6 meses', 'Solo amonestación escrita'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Operar maquinaria sin licencia Clase D y causar un accidente puede derivar en responsabilidad penal por cuasidelito de lesiones u homicidio, con penas de presidio, multas elevadas e inhabilitación para obtener cualquier licencia de conducir. La empresa que permitió la operación también enfrenta responsabilidades legales y administrativas.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_d'],
  },
];
