import type { Question } from './questionsData';

export const questionsClaseE: Question[] = [
  {
    id: 1500,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué tipo de licencia se requiere para conducir un vehículo de tracción animal en vías públicas en Chile?',
    opciones: ['No se requiere licencia', 'Licencia Clase E', 'Licencia Clase B', 'Licencia Clase C'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para conducir vehículos de tracción animal por vías públicas se requiere licencia Clase E, la cual habilita para operar este tipo de vehículos y ciclos con motor auxiliar. El conductor debe aprobar un examen teórico y demostrar conocimientos sobre normativa vial y bienestar animal.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1501,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué tipo de vías está prohibida la circulación de vehículos de tracción animal?',
    opciones: ['Calles residenciales', 'Autopistas y autovías', 'Caminos rurales no pavimentados', 'Calles con semáforos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos de tracción animal tienen prohibido circular por autopistas y autovías, ya que no pueden alcanzar las velocidades mínimas requeridas y representan un peligro para el tránsito de alta velocidad. Deben utilizar caminos rurales, calles urbanas y vías secundarias donde la velocidad sea compatible.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1502,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué elementos reflectantes debe llevar obligatoriamente un vehículo de tracción animal para circular de noche?',
    opciones: ['Solo una luz trasera roja', 'Elementos reflectantes en la parte delantera y trasera, y una luz roja trasera', 'No necesita elementos reflectantes', 'Solo cinta reflectante en las ruedas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos de tracción animal deben contar con elementos reflectantes visibles tanto en la parte delantera como trasera, además de una luz roja trasera para circular durante la noche o en condiciones de baja visibilidad. Estos elementos permiten que otros conductores los detecten a distancia suficiente para evitar colisiones.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1503,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Por qué lado de la calzada deben circular los vehículos de tracción animal?',
    opciones: ['Por el centro de la calzada', 'Por el lado izquierdo', 'Por el lado derecho, lo más cerca posible de la cuneta', 'Por la vereda cuando sea posible'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los vehículos de tracción animal deben circular siempre por el lado derecho de la calzada, lo más próximo posible a la cuneta o borde de la vía. Esto permite que los vehículos motorizados más rápidos los adelanten con seguridad por la izquierda, reduciendo el riesgo de accidentes.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1504,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la velocidad máxima recomendada para un vehículo de tracción animal en zona urbana?',
    opciones: ['30 km/h', '15 km/h', '10 km/h', '20 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los vehículos de tracción animal no deben superar los 10 km/h en zona urbana. Velocidades superiores pueden ser peligrosas tanto para el animal como para los peatones y otros usuarios de la vía. Además, a mayor velocidad el conductor tiene menor control sobre el animal y el vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1505,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer el conductor de un vehículo de tracción animal al aproximarse a un cruce peatonal?',
    opciones: ['Acelerar para pasar rápido', 'Detener al animal y ceder el paso a los peatones', 'Tocar una campana para advertir', 'Circular sin detenerse si no hay peatones visibles'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al aproximarse a un cruce peatonal, el conductor debe detener al animal y ceder el paso a los peatones que estén cruzando o esperando para cruzar. Los peatones siempre tienen prioridad en los cruces demarcados, independientemente del tipo de vehículo que se aproxime.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1506,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo debe reaccionar el conductor de tracción animal si el animal se asusta por un ruido fuerte?',
    opciones: ['Soltar las riendas inmediatamente', 'Sujetar firmemente las riendas, hablar con calma al animal y detenerse en lugar seguro', 'Golpear al animal para controlarlo', 'Saltar del vehículo rápidamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante un animal asustado, el conductor debe mantener el control sujetando firmemente las riendas, hablar al animal con voz calmada y firme, y buscar detenerse en un lugar seguro fuera de la calzada. Nunca se debe soltar las riendas ni golpear al animal, ya que esto empeoraría la situación y podría causar un accidente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1507,
    categoria: 'Medio Ambiente',
    pregunta: '¿Cuántas horas máximo debe trabajar un animal de tiro en un día según las normas de bienestar animal?',
    opciones: ['12 horas', '10 horas', '8 horas', '6 horas'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Según las normas de bienestar animal aplicables en Chile, un animal de tiro no debe trabajar más de 8 horas diarias. Además, debe contar con períodos de descanso adecuados, acceso a agua fresca y alimentación apropiada. El exceso de trabajo puede causar agotamiento, lesiones y sufrimiento innecesario al animal.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1508,
    categoria: 'Medio Ambiente',
    pregunta: '¿Cuál es un signo evidente de fatiga en un caballo utilizado para tracción?',
    opciones: ['Relinchar constantemente', 'Sudoración excesiva, respiración agitada y tropiezos frecuentes', 'Caminar más rápido de lo normal', 'Mover la cola continuamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los signos de fatiga en un caballo de tiro incluyen sudoración excesiva, respiración agitada y acelerada, tropiezos frecuentes, reducción del paso, cabeza baja y orejas caídas. Ante estos signos, el conductor debe detener el trabajo inmediatamente, proporcionar agua y sombra, y permitir al animal descansar adecuadamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1509,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué documento adicional debe portar el conductor de un vehículo de tracción animal además de la licencia?',
    opciones: ['Certificado de vacunación del animal', 'Pasaporte del animal', 'Permiso de circulación del vehículo y certificado sanitario del animal', 'Solo la licencia es suficiente'],
    respuestaCorrecta: 2,
    explicacionTexto: 'El conductor de un vehículo de tracción animal debe portar su licencia Clase E, el permiso de circulación del vehículo y un certificado sanitario del animal emitido por el SAG (Servicio Agrícola y Ganadero) que acredite que el animal está en condiciones de salud adecuadas para el trabajo.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1510,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precaución especial debe tomar el conductor de tracción animal al circular bajo lluvia?',
    opciones: ['Acelerar para llegar más rápido al destino', 'Reducir la velocidad ya que el pavimento mojado disminuye la tracción de las herraduras', 'Circular por el centro de la calzada', 'No hay precauciones especiales necesarias'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Bajo lluvia, las herraduras del animal pierden adherencia en pavimento mojado, aumentando el riesgo de resbalones y caídas. El conductor debe reducir la velocidad, evitar superficies lisas como adoquines mojados y procurar circular por superficies con mejor agarre. También debe usar elementos reflectantes adicionales por la baja visibilidad.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1511,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sanciones se aplican por maltrato animal durante la conducción de un vehículo de tracción animal?',
    opciones: ['Solo una advertencia verbal', 'Multa, decomiso del animal y posible pena de presidio según la Ley de Protección Animal', 'Solo una multa menor', 'No existen sanciones específicas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La Ley 20.380 de Protección de Animales y sus modificaciones establecen sanciones severas por maltrato animal, incluyendo multas, decomiso del animal y penas de presidio de hasta 3 años. Sobrecargar al animal, hacerlo trabajar enfermo o herido, o privarlo de agua y alimento constituyen formas de maltrato punibles.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1512,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el peso máximo de carga que puede transportar un vehículo de tracción animal equina?',
    opciones: ['Sin límite, depende del tamaño del carro', 'El peso no debe exceder la capacidad del animal, generalmente no más del 15% del peso del animal', 'Hasta 2 toneladas', 'Hasta 500 kg siempre'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La carga no debe exceder la capacidad del animal de tiro. Como regla general, el peso total del vehículo más la carga no debe superar el 15% del peso corporal del animal para tracción, considerando también la distancia a recorrer y las condiciones del terreno. Sobrecargar al animal constituye maltrato y es sancionable.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1513,
    categoria: 'Medio Ambiente',
    pregunta: '¿Qué obligación tiene el conductor respecto a los desechos del animal en la vía pública?',
    opciones: ['No tiene ninguna obligación', 'Debe recoger los desechos del animal para mantener la limpieza de la vía', 'Los desechos son responsabilidad del municipio', 'Solo debe recogerlos en zonas urbanas céntricas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor de un vehículo de tracción animal es responsable de recoger los desechos que el animal deje en la vía pública. Debe portar elementos adecuados como pala y bolsa para este fin. Los desechos en la calzada pueden provocar resbalones en otros vehículos y constituyen un problema de higiene pública.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1514,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué es un ciclo con motor auxiliar según la legislación chilena?',
    opciones: ['Una motocicleta de baja cilindrada', 'Una bicicleta equipada con un motor de hasta 50cc o eléctrico de hasta 0,5 kW', 'Cualquier vehículo de dos ruedas', 'Un scooter eléctrico de cualquier potencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un ciclo con motor auxiliar es una bicicleta equipada con un motor de combustión de hasta 50cc de cilindrada o un motor eléctrico de hasta 0,5 kW de potencia, que no puede superar los 50 km/h. Se clasifica dentro de la licencia Clase E y tiene regulaciones específicas distintas a las motocicletas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1515,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima permitida para un ciclo con motor auxiliar?',
    opciones: ['30 km/h', '45 km/h', '50 km/h', '60 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los ciclos con motor auxiliar no pueden superar los 50 km/h de velocidad máxima. Si un vehículo de estas características supera dicha velocidad o tiene un motor de mayor cilindrada o potencia, se clasifica como motocicleta y requiere licencia Clase C. La velocidad debe adaptarse siempre a las condiciones de la vía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1516,
    categoria: 'Conducción Segura',
    pregunta: '¿Es obligatorio el uso de casco para conducir un ciclo con motor auxiliar?',
    opciones: ['No, solo es recomendable', 'Sí, es obligatorio el uso de casco homologado', 'Solo fuera de zona urbana', 'Solo para menores de edad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El uso de casco homologado es obligatorio para conducir un ciclo con motor auxiliar. El casco debe estar debidamente certificado y abrochado correctamente. Conducir sin casco constituye una infracción grave y aumenta significativamente el riesgo de lesiones graves o muerte en caso de accidente.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1517,
    categoria: 'Conducción Segura',
    pregunta: '¿Puede un ciclo con motor auxiliar transportar pasajeros?',
    opciones: ['Sí, siempre que tenga un asiento trasero', 'No, solo puede transportar al conductor', 'Sí, hasta dos pasajeros', 'Solo si el pasajero es menor de 12 años'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los ciclos con motor auxiliar están diseñados para transportar exclusivamente al conductor. No cuentan con estructura ni asiento homologado para pasajeros. Llevar un pasajero altera el equilibrio del vehículo, aumenta la distancia de frenado y constituye una infracción a la normativa de tránsito.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1518,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es el principal riesgo al circular en un ciclo con motor auxiliar junto a vehículos pesados?',
    opciones: ['El ruido excesivo', 'La baja visibilidad del ciclo y el efecto de succión del vehículo pesado', 'La contaminación del escape', 'No existen riesgos especiales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los ciclos con motor auxiliar son difícilmente visibles para los conductores de vehículos pesados debido a sus puntos ciegos. Además, los camiones y buses generan un efecto de succión aerodinámico al pasar que puede desestabilizar al ciclomotor. Se debe mantener distancia lateral segura y evitar circular en los ángulos muertos de vehículos grandes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1519,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué sistema de frenos debe tener un ciclo con motor auxiliar?',
    opciones: ['Solo freno trasero', 'Freno delantero y trasero independientes', 'Solo freno de motor', 'Un solo freno en cualquier rueda'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Todo ciclo con motor auxiliar debe contar con freno delantero y freno trasero independientes, ambos en buen estado de funcionamiento. Utilizar solo un freno aumenta la distancia de frenado y puede provocar derrapes. El mantenimiento regular de los frenos es fundamental para la seguridad del conductor.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1520,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué luces debe tener un ciclo con motor auxiliar para circular de noche?',
    opciones: ['Solo una luz trasera roja', 'Luz delantera blanca, luz trasera roja y elementos reflectantes laterales', 'Solo elementos reflectantes', 'Las mismas luces que una motocicleta'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para circular de noche, un ciclo con motor auxiliar debe contar con luz delantera blanca, luz trasera roja y elementos reflectantes laterales. Circular sin estas luces en horario nocturno constituye una infracción grave y pone en serio riesgo la vida del conductor al ser prácticamente invisible para otros vehículos.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1521,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué técnica de conducción defensiva es más importante para un conductor de tracción animal en una intersección?',
    opciones: ['Acelerar para cruzar rápido', 'Detenerse completamente, verificar el tránsito en ambas direcciones y cruzar solo cuando sea seguro', 'Confiar en que los demás conductores le cederán el paso', 'Usar una bocina para advertir su presencia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En las intersecciones, el conductor de tracción animal debe detenerse completamente y verificar el tránsito en ambas direcciones antes de cruzar. Dado que estos vehículos son lentos y poco visibles, deben asegurarse de tener espacio y tiempo suficiente para completar el cruce sin obstaculizar el tránsito de vehículos motorizados.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1522,
    categoria: 'Medio Ambiente',
    pregunta: '¿Cuál es la temperatura ambiente máxima recomendada para hacer trabajar a un animal de tiro?',
    opciones: ['40°C', '35°C', '30°C', 'No existe límite de temperatura'],
    respuestaCorrecta: 2,
    explicacionTexto: 'No se recomienda hacer trabajar a un animal de tiro cuando la temperatura ambiente supera los 30°C, ya que el esfuerzo físico combinado con el calor puede provocar golpe de calor, deshidratación severa y colapso del animal. En días calurosos se debe reducir la jornada laboral y proporcionar agua y sombra frecuentemente.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1523,
    categoria: 'Conducción Segura',
    pregunta: '¿Cada cuánto tiempo debe detenerse el conductor para dar agua al animal de tiro durante un trayecto largo?',
    opciones: ['Cada 4 horas', 'Cada 2 horas como máximo', 'Solo al finalizar el recorrido', 'Cada 30 minutos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Durante trayectos largos, el conductor debe detenerse al menos cada 2 horas para proporcionar agua fresca al animal y permitirle un breve descanso. La deshidratación puede provocar problemas graves de salud e incluso la muerte del animal. En días calurosos, las paradas deben ser más frecuentes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1524,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué norma regula el bienestar de los animales utilizados en tracción en Chile?',
    opciones: ['Solo la Ley de Tránsito', 'La Ley 20.380 sobre Protección de Animales', 'No existe normativa específica', 'Solo ordenanzas municipales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La Ley 20.380 sobre Protección de Animales establece el marco legal para el bienestar de los animales de trabajo, incluyendo los de tracción. Esta ley prohíbe el maltrato, la sobrecarga, el trabajo de animales enfermos o heridos, y establece condiciones mínimas de cuidado, alimentación y descanso.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1525,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué estado deben tener las herraduras del animal de tiro para circular de forma segura?',
    opciones: ['No es necesario que tenga herraduras', 'Deben estar en buen estado, sin desgaste excesivo y correctamente colocadas', 'Solo importa si circula por asfalto', 'Las herraduras son opcionales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las herraduras deben estar en buen estado, sin desgaste excesivo y correctamente colocadas por un herrero calificado. Herraduras desgastadas o mal puestas pueden provocar resbalones del animal en el pavimento, lesiones en los cascos y problemas de locomoción que comprometen la seguridad vial.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1526,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Por qué los vehículos de tracción animal representan un riesgo especial en curvas?',
    opciones: ['Porque aceleran en las curvas', 'Porque son lentos, poco visibles y el animal puede reaccionar de forma impredecible', 'Porque ocupan mucho espacio lateral', 'No representan riesgo especial en curvas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En las curvas, los vehículos de tracción animal son especialmente vulnerables porque su baja velocidad los hace difíciles de anticipar por otros conductores, tienen baja visibilidad y el animal puede reaccionar de forma impredecible ante estímulos. El conductor debe extremar precauciones, señalizar y mantenerse lo más a la derecha posible.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1527,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Está permitido que un vehículo de tracción animal circule por una vía con pendiente pronunciada?',
    opciones: ['Sí, sin restricciones', 'Solo si el animal puede manejar la carga sin esfuerzo excesivo', 'No, está totalmente prohibido', 'Solo en descenso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un vehículo de tracción animal puede circular por vías con pendiente siempre que el animal pueda manejar la carga sin esfuerzo excesivo. En pendientes pronunciadas debe reducirse la carga, utilizar frenos mecánicos del carro en el descenso y evitar subidas que puedan causar agotamiento o lesiones al animal.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1528,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué elemento mecánico de seguridad debe tener un carro de tracción animal para circular en pendientes?',
    opciones: ['Motor auxiliar', 'Sistema de freno mecánico (calza o freno de tambor)', 'Sistema de dirección hidráulica', 'Suspensión independiente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Todo carro de tracción animal debe contar con un sistema de freno mecánico, como calzas o freno de tambor, que permita detener y mantener detenido el vehículo en pendientes. Sin frenos, el peso del carro cargado puede empujar al animal cuesta abajo de forma descontrolada, provocando accidentes graves.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1529,
    categoria: 'Medio Ambiente',
    pregunta: '¿Cuál es una ventaja ambiental de los vehículos de tracción animal frente a los motorizados?',
    opciones: ['Son más rápidos', 'No generan emisiones de gases contaminantes', 'Pueden transportar más carga', 'Requieren menos mantenimiento'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos de tracción animal no generan emisiones de gases contaminantes como CO2, monóxido de carbono o material particulado, a diferencia de los vehículos con motor de combustión. Esto los convierte en una alternativa de transporte más amigable con el medio ambiente, especialmente en zonas rurales y para recorridos cortos.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1530,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué horario se restringe generalmente la circulación de vehículos de tracción animal en zonas urbanas?',
    opciones: ['No existe restricción horaria', 'Durante las horas de mayor congestión vehicular, según ordenanza municipal', 'Solo pueden circular de noche', 'Solo entre 6:00 y 18:00'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Muchos municipios establecen restricciones horarias para la circulación de vehículos de tracción animal en zonas urbanas, especialmente durante las horas punta de mayor congestión vehicular. Estas restricciones varían según la comuna y están definidas por ordenanzas municipales que buscan mantener la fluidez del tránsito.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1531,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe estar distribuida la carga en un carro de tracción animal?',
    opciones: ['Toda la carga hacia adelante', 'Equilibrada y bien sujeta, con el peso centrado sobre el eje', 'Toda hacia atrás para aliviar al animal', 'No importa la distribución'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La carga debe estar equilibrada y bien sujeta, con el peso centrado sobre el eje del carro. Una carga desequilibrada hacia adelante sobrecarga al animal, y hacia atrás puede levantar las varas y desestabilizar el vehículo. La carga mal distribuida también afecta la maniobrabilidad y puede provocar vuelcos en curvas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1532,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué debe hacer el conductor de un ciclo con motor auxiliar al ser adelantado por un vehículo de gran tamaño?',
    opciones: ['Acelerar para mantenerse a la par', 'Mantener la trayectoria firme, sujetar bien el manillar y reducir ligeramente la velocidad', 'Detenerse inmediatamente', 'Cambiar de pista hacia la izquierda'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al ser adelantado por un vehículo grande, el conductor del ciclo con motor debe mantener una trayectoria firme y recta, sujetar bien el manillar para resistir la turbulencia aerodinámica, y reducir ligeramente la velocidad. No debe hacer movimientos bruscos ni intentar competir con el vehículo que adelanta.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1533,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué revisión básica debe realizar el conductor de un ciclo con motor auxiliar antes de cada viaje?',
    opciones: ['Solo verificar el combustible', 'Revisar frenos, neumáticos, luces, cadena y nivel de combustible o batería', 'Solo verificar las luces', 'No requiere revisión previa'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de cada viaje, el conductor debe revisar el estado de los frenos delantero y trasero, la presión y estado de los neumáticos, el funcionamiento de las luces, la tensión y lubricación de la cadena, y el nivel de combustible o carga de la batería. Estas revisiones previenen averías y accidentes durante la circulación.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1534,
    categoria: 'Conducción Segura',
    pregunta: '¿Cada cuánto tiempo se recomienda realizar el mantenimiento general del motor de un ciclo con motor auxiliar?',
    opciones: ['Cada 5.000 km', 'Cada 1.000 a 2.000 km o según recomendación del fabricante', 'Solo cuando presente fallas', 'Una vez al año'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El mantenimiento general del motor de un ciclo con motor auxiliar debe realizarse cada 1.000 a 2.000 km o según las recomendaciones del fabricante. Incluye cambio de aceite, limpieza del filtro de aire, revisión de bujía, ajuste del carburador y verificación de la transmisión. Un mantenimiento adecuado prolonga la vida útil y mejora la seguridad.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1535,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Necesita un ciclo con motor auxiliar permiso de circulación?',
    opciones: ['No, está exento de permiso', 'Sí, debe tener permiso de circulación vigente', 'Solo si circula fuera de zona urbana', 'Solo si tiene motor de combustión'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Todo ciclo con motor auxiliar que circule por vías públicas debe contar con permiso de circulación vigente, al igual que cualquier otro vehículo motorizado. Debe pagarse anualmente antes del 31 de marzo. Circular sin permiso vigente constituye una infracción que puede resultar en multa y retención del vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1536,
    categoria: 'Medio Ambiente',
    pregunta: '¿Qué tipo de combustible utilizan la mayoría de los ciclos con motor auxiliar de combustión?',
    opciones: ['Diésel', 'Mezcla de gasolina con aceite de dos tiempos', 'Gas natural', 'Gasolina pura de 97 octanos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La mayoría de los ciclos con motor auxiliar de combustión utilizan motores de dos tiempos que requieren una mezcla de gasolina con aceite lubricante en proporciones específicas indicadas por el fabricante (generalmente 1:50 o 1:25). Usar la proporción incorrecta puede dañar el motor o generar emisiones excesivas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1537,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es la distancia de seguimiento segura que debe mantener un ciclo con motor auxiliar respecto al vehículo que lo precede?',
    opciones: ['1 segundo', '2 segundos como mínimo', '5 metros fijos', 'No necesita mantener distancia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un ciclo con motor auxiliar debe mantener al menos 2 segundos de distancia de seguimiento respecto al vehículo que lo precede. Esta distancia permite al conductor reaccionar ante frenadas bruscas. En condiciones adversas como lluvia o pavimento mojado, la distancia debe aumentarse a 4 segundos o más.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1538,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puede un ciclo con motor auxiliar circular por ciclovías?',
    opciones: ['Sí, siempre', 'No, debe circular por la calzada', 'Solo si su velocidad es inferior a 25 km/h', 'Solo los eléctricos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los ciclos con motor auxiliar deben circular por la calzada, no por las ciclovías, ya que estas están destinadas exclusivamente a bicicletas convencionales y bicicletas de pedaleo asistido de baja velocidad. El motor auxiliar los clasifica como vehículos motorizados que deben compartir la calzada con el resto del tránsito vehicular.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1539,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué vestimenta es recomendable para conducir un ciclo con motor auxiliar además del casco?',
    opciones: ['Ropa ligera y cómoda', 'Chaleco reflectante, guantes y calzado cerrado', 'No hay recomendaciones especiales', 'Solo zapatos deportivos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Además del casco obligatorio, se recomienda usar chaleco reflectante para mejorar la visibilidad, guantes para proteger las manos y mejorar el agarre, y calzado cerrado y firme. Ropa ajustada evita que se enganche con partes del vehículo. Estas medidas reducen significativamente la gravedad de las lesiones en caso de caída.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1540,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué hacer si el animal de tiro se niega a avanzar en medio de la calzada?',
    opciones: ['Golpearlo para que avance', 'Encender las luces de emergencia, intentar calmarlo y moverlo hacia el costado de la vía', 'Abandonar el vehículo', 'Esperar indefinidamente a que se mueva solo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si el animal se niega a avanzar, el conductor debe señalizar la detención con elementos reflectantes o luces, intentar calmar al animal con voz suave, verificar si hay algún problema de salud o arnés y moverlo hacia el costado de la vía lo más pronto posible para no obstaculizar el tránsito.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1541,
    categoria: 'Medio Ambiente',
    pregunta: '¿Qué condiciones mínimas de alojamiento debe tener un animal utilizado para tracción cuando no está trabajando?',
    opciones: ['Puede permanecer atado en la calle', 'Un espacio adecuado con techo, agua, alimento y espacio para moverse', 'Solo necesita agua', 'No hay exigencias legales al respecto'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El animal de tracción debe contar con un espacio de alojamiento adecuado que incluya protección contra la intemperie, acceso permanente a agua limpia, alimentación apropiada y suficiente espacio para moverse. La Ley de Protección Animal exige condiciones mínimas de bienestar que garanticen la salud física y mental del animal.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1542,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué edad mínima se requiere para obtener la licencia Clase E?',
    opciones: ['16 años', '18 años', '21 años', '14 años'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para obtener la licencia Clase E se requiere tener al menos 18 años de edad. El postulante debe aprobar un examen teórico sobre normativa de tránsito, señalización y bienestar animal, además de un examen psicotécnico. No se requiere poseer previamente otra clase de licencia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1543,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el principal riesgo de un ciclo con motor auxiliar en caminos de tierra o ripio?',
    opciones: ['Mayor consumo de combustible', 'Pérdida de estabilidad por la superficie irregular y suelta', 'Daño al motor por el polvo', 'No hay riesgos adicionales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En caminos de tierra o ripio, el principal riesgo es la pérdida de estabilidad debido a la superficie irregular y suelta. Las ruedas pequeñas del ciclo con motor son especialmente vulnerables a piedras y baches. El conductor debe reducir significativamente la velocidad, evitar frenadas bruscas y mantener ambas manos en el manillar.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1544,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué precaución debe tomar el conductor de tracción animal al circular junto a una obra en construcción?',
    opciones: ['Circular normalmente', 'Reducir la velocidad, mantener distancia y estar preparado para una reacción del animal ante ruidos fuertes', 'Acelerar para pasar rápido la zona', 'Desmontar y llevar al animal a pie'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Las zonas de construcción generan ruidos fuertes, vibraciones y movimientos que pueden asustar al animal. El conductor debe reducir la velocidad, mantener distancia de la obra, hablar con calma al animal y estar preparado para controlar cualquier reacción de nerviosismo. Si es posible, conviene buscar una ruta alternativa.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1545,
    categoria: 'Medio Ambiente',
    pregunta: '¿Cuál es la alimentación adecuada para un caballo de tiro durante jornadas de trabajo?',
    opciones: ['Solo agua', 'Heno, avena, agua abundante y suplementos minerales según el esfuerzo', 'Solo pasto verde', 'Cualquier alimento disponible'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un caballo de tiro requiere una alimentación equilibrada que incluya heno o pasto como base, avena u otro concentrado energético proporcional al esfuerzo, agua fresca abundante y suplementos minerales. La alimentación inadecuada debilita al animal, reduce su rendimiento y puede provocar enfermedades como cólicos o laminitis.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1546,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué señalización debe llevar un vehículo de tracción animal durante el día?',
    opciones: ['No requiere señalización de día', 'Banderín naranja o rojo triangular visible en la parte trasera', 'Solo la placa patente', 'Luces encendidas como un automóvil'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Durante el día, los vehículos de tracción animal deben llevar un banderín triangular de color naranja o rojo en la parte trasera que sea visible para los conductores que se aproximan por detrás. Este elemento alerta sobre la presencia de un vehículo lento en la calzada y reduce el riesgo de colisiones por alcance.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1547,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué tipo de arnés o aparejo se debe utilizar en un animal de tracción?',
    opciones: ['Cualquier cuerda o amarre disponible', 'Un arnés adecuado al tamaño del animal que distribuya el esfuerzo sin causar heridas', 'Solo un collar simple', 'No es necesario un arnés específico'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Se debe utilizar un arnés adecuado al tamaño y contextura del animal que distribuya el esfuerzo de tracción de manera uniforme sin causar rozaduras, heridas o presión excesiva. Un arnés mal ajustado o inadecuado puede provocar lesiones graves en la piel, músculos y articulaciones del animal.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1548,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es el mayor peligro para un ciclo con motor auxiliar en una rotonda?',
    opciones: ['La velocidad excesiva', 'La falta de visibilidad y el riesgo de no ser visto por otros vehículos al ingresar o salir', 'Las señales de tránsito', 'El viento lateral'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En una rotonda, el mayor peligro para un ciclo con motor auxiliar es la falta de visibilidad y el riesgo de no ser visto por otros vehículos. Al ingresar, el conductor debe ceder el paso a quienes ya circulan dentro y señalizar claramente sus intenciones de salida. Se recomienda circular por la pista exterior y extremar la precaución.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
  {
    id: 1549,
    categoria: 'Medio Ambiente',
    pregunta: '¿Por qué es importante revisar los cascos del animal de tiro regularmente?',
    opciones: ['Solo por razones estéticas', 'Porque cascos dañados o con herraduras desgastadas causan dolor, cojera y riesgo de resbalones', 'No es necesario revisar los cascos', 'Solo para cumplir con la ley'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los cascos del animal deben revisarse regularmente porque herraduras desgastadas o mal puestas causan dolor y cojera, y aumentan el riesgo de resbalones en el pavimento. Además, pueden acumularse piedras o desarrollarse infecciones en la ranilla. Un herrero profesional debe revisar y cambiar las herraduras cada 6 a 8 semanas.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_e'],
  },
];
