import type { Question } from './questionsData';

export const questionsA4: Question[] = [
  {
    id: 1200,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es el peso bruto vehicular máximo permitido para un camión simple en Chile sin autorización especial?',
    opciones: ['35.000 kg', '45.000 kg', '50.000 kg', '60.000 kg'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En Chile, el peso bruto vehicular máximo permitido para un camión simple es de 45.000 kg según la normativa vigente. Superar este límite sin autorización especial constituye una infracción grave y puede dañar la infraestructura vial, especialmente puentes y pavimentos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1201,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué documento adicional debe portar un conductor de vehículo de carga además de los documentos habituales?',
    opciones: ['Certificado de nacimiento', 'Guía de despacho o factura de la carga transportada', 'Certificado de estudios', 'Tarjeta de crédito empresarial'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor de un vehículo de carga debe portar la guía de despacho o factura que acredite el origen y destino de la mercancía transportada. Este documento es exigido por Carabineros y el Servicio de Impuestos Internos para verificar la legalidad del transporte.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1202,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la velocidad máxima permitida para camiones en autopistas en Chile?',
    opciones: ['80 km/h', '90 km/h', '100 km/h', '120 km/h'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los camiones y vehículos de carga tienen una velocidad máxima de 100 km/h en autopistas, inferior a la de vehículos livianos. Esta restricción se debe a la mayor distancia de frenado, el centro de gravedad más alto y el mayor riesgo de volcamiento a altas velocidades.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1203,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué restricción horaria aplica a los camiones en zonas urbanas de Santiago?',
    opciones: ['No pueden circular de noche', 'Tienen restricción en horarios punta según tonelaje', 'Solo pueden circular los fines de semana', 'No tienen restricción horaria'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los camiones de cierto tonelaje tienen restricción de circulación en horarios punta en zonas urbanas de Santiago para evitar congestión. Los horarios y las vías restringidas varían según el peso del vehículo y son establecidos por la autoridad de transporte regional.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1204,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué es la Hoja de Seguridad del Transporte (HDS) y cuándo es obligatoria?',
    opciones: ['Un seguro contra robos de carga', 'Un documento que detalla las características de materiales peligrosos transportados', 'Un certificado de revisión técnica especial', 'Un permiso municipal para camiones'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La Hoja de Seguridad del Transporte es un documento obligatorio al transportar sustancias peligrosas. Contiene información sobre la composición, riesgos, medidas de emergencia y primeros auxilios ante derrames o exposición. Debe estar siempre accesible en la cabina del conductor.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1205,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe distribuirse correctamente la carga en un camión?',
    opciones: ['Toda la carga al frente para mejor tracción', 'Toda la carga atrás para liberar el eje delantero', 'Distribuida uniformemente con el centro de gravedad lo más bajo posible', 'No importa la distribución si no excede el peso máximo'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La carga debe distribuirse uniformemente manteniendo el centro de gravedad lo más bajo posible. Una mala distribución puede provocar inestabilidad, volcamiento en curvas, desgaste desigual de neumáticos y sobrecarga de ejes, comprometiendo la seguridad del vehículo y de otros usuarios de la vía.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1206,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el principal riesgo de un camión con carga mal asegurada al frenar bruscamente?',
    opciones: ['Se apaga el motor', 'La carga se desplaza hacia adelante pudiendo aplastar la cabina', 'Se pincha un neumático', 'Se activa la alarma del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al frenar bruscamente, una carga mal asegurada se desplaza hacia adelante por inercia, pudiendo atravesar la cabina y causar lesiones fatales al conductor. También puede caer a la vía provocando accidentes a otros vehículos. Es fundamental verificar los amarres antes y durante el viaje.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1207,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué elementos se utilizan para asegurar la carga en un camión plataforma?',
    opciones: ['Solo cuerdas de nylon', 'Cintas de amarre (trinquetes), cadenas, cuñas y redes de contención', 'Solamente plástico envolvente', 'Clavos y tornillos en la plataforma'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para asegurar la carga se utilizan cintas de amarre con trinquetes (ratchets), cadenas con tensores, cuñas para evitar desplazamientos, redes de contención y esquineros protectores. Cada tipo de carga requiere un método específico de sujeción según su peso, forma y características.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1208,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe verificar el conductor antes de iniciar un viaje con carga?',
    opciones: ['Solo el nivel de combustible', 'El estado de los amarres, distribución de carga, presión de neumáticos y documentación', 'Solo que la carga esté cubierta con lona', 'Solo los espejos retrovisores'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de iniciar un viaje, el conductor debe realizar una inspección completa: verificar amarres y sujeción de la carga, correcta distribución del peso, presión de neumáticos, funcionamiento de luces, frenos, documentación de la carga y del vehículo. Esta rutina previene accidentes y detenciones por incumplimiento.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1209,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué señalización debe llevar un vehículo que transporta materiales peligrosos?',
    opciones: ['Una bandera roja en la antena', 'Rombos de identificación de Naciones Unidas según la clase de peligro', 'Una luz amarilla intermitente en el techo', 'No requiere señalización especial'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos que transportan materiales peligrosos deben exhibir rombos de identificación según la clasificación de Naciones Unidas que indican el tipo de peligro: explosivo, inflamable, tóxico, corrosivo, etc. Estos rombos deben ser visibles por los cuatro costados del vehículo y facilitan la respuesta en caso de emergencia.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1210,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuántas clases de sustancias peligrosas reconoce la normativa de transporte en Chile?',
    opciones: ['5 clases', '7 clases', '9 clases', '12 clases'],
    respuestaCorrecta: 2,
    explicacionTexto: 'La normativa reconoce 9 clases de sustancias peligrosas según la clasificación de Naciones Unidas: explosivos, gases, líquidos inflamables, sólidos inflamables, sustancias oxidantes, sustancias tóxicas, materiales radiactivos, sustancias corrosivas y sustancias peligrosas varias. Cada clase tiene requisitos específicos de transporte.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1211,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es el efecto péndulo en un camión con carga líquida?',
    opciones: ['El balanceo del volante', 'El movimiento oscilante del líquido dentro del tanque que afecta la estabilidad', 'La vibración del motor a bajas revoluciones', 'El desgaste pendular de los neumáticos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El efecto péndulo ocurre cuando el líquido dentro de un tanque se mueve de un lado a otro durante maniobras como curvas o frenados, generando fuerzas que pueden desestabilizar el vehículo e incluso provocar volcamientos. Los tanques con mamparas o compartimentos internos minimizan este efecto.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1212,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué es más peligroso transportar un tanque parcialmente lleno que uno completamente lleno?',
    opciones: ['Porque pesa menos y el viento lo afecta más', 'Porque el líquido tiene espacio para moverse y genera oleaje interno', 'Porque el motor se sobrecalienta', 'Porque los frenos funcionan peor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un tanque parcialmente lleno permite que el líquido se desplace libremente, generando oleaje interno que afecta la estabilidad del vehículo en curvas, frenados y aceleraciones. Un tanque lleno limita el movimiento del líquido. Los tanques cisterna deben tener mamparas internas para reducir este efecto.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1213,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué función cumple el tacógrafo en un vehículo de carga?',
    opciones: ['Mide la temperatura del motor', 'Registra velocidad, distancia recorrida y tiempos de conducción y descanso', 'Controla la presión de los neumáticos', 'Mide el consumo de combustible'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El tacógrafo es un dispositivo que registra automáticamente la velocidad, la distancia recorrida y los tiempos de conducción, descanso y trabajo del conductor. Es obligatorio en vehículos de carga y transporte y permite a las autoridades fiscalizar el cumplimiento de las normas de descanso obligatorio.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1214,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuántas horas continuas puede conducir un conductor de camión antes de tomar un descanso obligatorio?',
    opciones: ['3 horas', '5 horas', '8 horas', '10 horas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un conductor profesional de carga puede conducir un máximo de 5 horas continuas antes de tomar un descanso obligatorio de al menos 30 minutos. En un período de 24 horas, no debe exceder las 10 horas de conducción efectiva. Estas normas previenen la fatiga al volante, causa frecuente de accidentes graves.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1215,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es el tiempo mínimo de descanso obligatorio después de 5 horas continuas de conducción?',
    opciones: ['15 minutos', '30 minutos', '1 hora', '2 horas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Después de 5 horas continuas de conducción, el conductor debe realizar una pausa mínima de 30 minutos. Este descanso permite recuperar la concentración y reducir la fatiga. El incumplimiento de los tiempos de descanso es una infracción grave y el tacógrafo registra estos períodos para su fiscalización.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1216,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué distancia de seguimiento debe mantener un camión cargado respecto al vehículo que lo precede?',
    opciones: ['La misma que un auto liviano', 'Al menos el doble de la distancia de un vehículo liviano', 'No hay regla específica', '1 metro por cada km/h de velocidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un camión cargado necesita al menos el doble de distancia de frenado que un vehículo liviano debido a su mayor peso e inercia. A 80 km/h, un camión puede necesitar más de 100 metros para detenerse completamente. Mantener una distancia adecuada es fundamental para evitar colisiones.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1217,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es el punto ciego en un camión y por qué es especialmente peligroso?',
    opciones: ['Es un desperfecto en el parabrisas', 'Son zonas alrededor del camión no visibles por los espejos, donde pueden ocultarse vehículos o peatones', 'Es una falla en las luces traseras', 'Es un problema de visión del conductor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los puntos ciegos de un camión son significativamente más grandes que los de un vehículo liviano. Existen zonas amplias a ambos lados, detrás y directamente frente al camión donde otros vehículos, ciclistas y peatones no son visibles. Los espejos adicionales y cámaras ayudan pero no eliminan completamente estos ángulos muertos.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1218,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué sistema de frenos es obligatorio en vehículos de carga pesada?',
    opciones: ['Solo frenos de disco en las ruedas delanteras', 'Sistema de frenos de aire comprimido (neumáticos)', 'Solo freno de mano mecánico', 'Frenos hidráulicos convencionales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos de carga pesada utilizan sistemas de frenos de aire comprimido (neumáticos) porque pueden generar la fuerza necesaria para detener vehículos de gran tonelaje. Este sistema incluye compresor, tanques de aire, válvulas de freno y cámaras de freno. A diferencia de los frenos hidráulicos, si hay una fuga, los frenos se activan automáticamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1219,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué indica la presión baja en el sistema de frenos de aire de un camión?',
    opciones: ['Que los frenos están funcionando correctamente', 'Que existe una fuga de aire y los frenos pueden fallar', 'Que se necesita cambiar el aceite', 'Que los neumáticos están desinflados'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una presión baja en el sistema de frenos de aire indica una posible fuga en el sistema. Si la presión cae por debajo del nivel mínimo de seguridad, los frenos de emergencia se activan automáticamente. El conductor debe verificar la presión antes de cada viaje y detenerse inmediatamente si la alarma de baja presión se activa.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1220,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué precaución especial debe tomar un camión al circular por un puente?',
    opciones: ['Acelerar para cruzar rápidamente', 'Verificar la capacidad de carga del puente y no exceder el peso máximo permitido', 'Circular por el centro del puente', 'Encender las luces altas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de cruzar un puente, el conductor debe verificar que el peso de su vehículo no exceda la capacidad máxima señalizada. Exceder el límite de peso puede causar daños estructurales al puente e incluso su colapso. En caso de duda, debe buscar una ruta alternativa.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1221,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es el fenómeno de "tijera" en un camión articulado?',
    opciones: ['Cuando las puertas se abren durante la marcha', 'Cuando el remolque gira sobre el punto de enganche y se pliega contra la cabina', 'Cuando la dirección se endurece', 'Cuando se cortan las correas del motor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El efecto tijera ocurre cuando el semirremolque gira sobre la quinta rueda y se pliega contra la cabina del tractocamión, formando un ángulo en forma de V. Generalmente se produce por frenadas bruscas en superficies resbaladizas. Para prevenirlo se debe evitar frenar bruscamente y mantener velocidades adecuadas en curvas.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1222,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué es la quinta rueda en un tractocamión?',
    opciones: ['Una rueda de repuesto especial', 'El dispositivo de acoplamiento entre el tractocamión y el semirremolque', 'La rueda central del eje trasero', 'Un sistema de dirección auxiliar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La quinta rueda es el mecanismo de enganche ubicado en la parte trasera del tractocamión que permite acoplar y desacoplar el semirremolque. Debe ser inspeccionada regularmente para verificar que el enganche está seguro, que no haya desgaste excesivo y que el sistema de bloqueo funcione correctamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1223,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un conductor de camión al descender una pendiente pronunciada?',
    opciones: ['Poner el vehículo en neutro para ahorrar combustible', 'Usar una marcha baja y el freno motor, evitando usar solo los frenos de servicio', 'Frenar constantemente con el pedal de freno', 'Apagar el motor y frenar con el freno de mano'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al descender pendientes pronunciadas, se debe utilizar una marcha baja para aprovechar el freno motor y complementar con los frenos de servicio de forma intermitente. Usar solo los frenos de servicio continuamente puede sobrecalentarlos (fading), provocando su pérdida total. Los retardadores electromagnéticos también ayudan a controlar la velocidad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1224,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué es el retardador (retarder) en un camión?',
    opciones: ['Un dispositivo que limita la velocidad máxima', 'Un sistema auxiliar de frenado que reduce el desgaste de los frenos principales', 'Un regulador de revoluciones del motor', 'Un sistema de control de emisiones'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El retardador es un sistema auxiliar de frenado que puede ser electromagnético o hidráulico. Reduce la velocidad del vehículo sin utilizar los frenos de servicio, evitando su sobrecalentamiento en descensos prolongados. Es especialmente útil en cuestas largas y contribuye significativamente a la seguridad del vehículo de carga.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1225,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuáles son las dimensiones máximas permitidas para un camión en Chile?',
    opciones: ['Largo 12 m, ancho 2,6 m, alto 4,2 m', 'Largo 15 m, ancho 3 m, alto 5 m', 'Largo 20 m, ancho 2,6 m, alto 4,2 m', 'No hay límites de dimensiones'],
    respuestaCorrecta: 0,
    explicacionTexto: 'Las dimensiones máximas para un camión simple en Chile son: largo máximo de 12 metros, ancho máximo de 2,6 metros y altura máxima de 4,2 metros. Para conjuntos articulados las dimensiones varían. Exceder estos límites requiere autorización especial y escolta para cargas sobredimensionadas.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1226,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué longitud máxima puede tener un tracto-camión con semirremolque en Chile?',
    opciones: ['15,5 metros', '18,6 metros', '20,5 metros', '22 metros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un tracto-camión con semirremolque puede tener una longitud máxima de 18,6 metros en Chile. Los bitrenes o vehículos de mayor longitud requieren permisos especiales y deben circular por rutas autorizadas. Estos límites aseguran la maniobrabilidad del vehículo y la seguridad en las vías.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1227,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo debe actuar un conductor de camión ante viento lateral fuerte?',
    opciones: ['Acelerar para pasar rápido la zona', 'Reducir la velocidad, sujetar firmemente el volante y estar atento a ráfagas', 'Detenerse inmediatamente en la calzada', 'Circular por el carril contrario'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante viento lateral fuerte, el conductor debe reducir la velocidad, sujetar firmemente el volante con ambas manos y estar preparado para corregir la dirección ante ráfagas repentinas. Los camiones vacíos o con carga ligera son especialmente vulnerables al viento. En puentes y zonas expuestas el riesgo es mayor.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1228,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué riesgo especial tienen los camiones con carga alta al pasar bajo un paso a desnivel?',
    opciones: ['Mayor consumo de combustible', 'Impactar la estructura si la altura del vehículo excede el gálibo', 'Pérdida de señal de radio', 'Ningún riesgo especial'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los camiones con carga alta pueden impactar pasos a desnivel, puentes o túneles si la altura total del vehículo con carga supera el gálibo (altura libre) de la estructura. El conductor debe conocer la altura total de su vehículo cargado y respetar las señales de altura máxima. Un impacto puede ser catastrófico.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1229,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precauciones debe tomar un camión al maniobrar en reversa?',
    opciones: ['Solo mirar por los espejos', 'Usar señalero, verificar puntos ciegos, y si es posible contar con un guía externo', 'Tocar la bocina continuamente', 'No se necesitan precauciones especiales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al maniobrar en reversa, el conductor debe activar las luces de retroceso, verificar todos los puntos ciegos, usar los espejos y preferiblemente contar con un ayudante externo que guíe la maniobra. Muchos accidentes graves ocurren en maniobras de retroceso por la limitada visibilidad trasera de los camiones.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1230,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué pista debe circular un camión de carga en una vía de varios carriles?',
    opciones: ['En cualquier pista disponible', 'En la pista derecha, usando la izquierda solo para adelantar', 'Siempre en la pista izquierda', 'En la pista central'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los camiones deben circular por la pista derecha en vías de varios carriles, utilizando las pistas izquierdas solo para adelantar. Esto permite el flujo ordenado del tránsito y facilita que los vehículos más rápidos los adelanten de manera segura. Circular por la pista izquierda sin adelantar es una infracción.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1231,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es la carga indivisible y qué permisos requiere para su transporte?',
    opciones: ['Carga que no se puede dividir como maquinaria pesada, requiere permiso especial de la Dirección de Vialidad', 'Carga de alimentos que no se puede separar', 'Carga que viaja sellada por aduanas', 'Cualquier carga en contenedor'],
    respuestaCorrecta: 0,
    explicacionTexto: 'La carga indivisible es aquella que por su naturaleza no puede ser fraccionada sin afectar su integridad, como maquinaria pesada, vigas de gran longitud o transformadores eléctricos. Su transporte requiere permisos especiales, rutas autorizadas, escolta y señalización adicional cuando excede las dimensiones reglamentarias.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1232,
    categoria: 'Mecánica Básica',
    pregunta: '¿Con qué frecuencia debe verificarse la presión de los neumáticos en un camión de carga?',
    opciones: ['Una vez al mes', 'Antes de cada viaje', 'Solo cuando se ve el neumático desinflado', 'En cada revisión técnica'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La presión de los neumáticos debe verificarse antes de cada viaje y cuando el neumático está frío. Los neumáticos con presión incorrecta aumentan el consumo de combustible, se desgastan irregularmente y pueden reventar, especialmente bajo cargas pesadas. Un reventón de neumático en un camión a velocidad puede causar pérdida total del control.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1233,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué función cumplen los guardabarros o faldones en un camión?',
    opciones: ['Solo decoración', 'Evitan que piedras, agua y barro sean lanzados hacia otros vehículos', 'Mejoran la aerodinámica', 'Protegen el chasis de la corrosión'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los guardabarros y faldones evitan que las ruedas del camión lancen piedras, agua, barro y otros elementos hacia los vehículos que circulan detrás o al costado. Su ausencia o mal estado constituye una infracción y un riesgo para otros usuarios de la vía, ya que las proyecciones pueden dañar parabrisas y causar accidentes.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1234,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo afecta la carga al centro de gravedad y la estabilidad del camión en curvas?',
    opciones: ['No lo afecta', 'Una carga alta eleva el centro de gravedad aumentando el riesgo de volcamiento en curvas', 'Solo afecta la velocidad máxima', 'Solo afecta el consumo de combustible'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una carga ubicada en posición alta eleva el centro de gravedad del camión, aumentando significativamente el riesgo de volcamiento en curvas, cambios de dirección y maniobras evasivas. El conductor debe reducir la velocidad en curvas proporcionalmente a la altura de la carga y su peso total.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1235,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué es el peso por eje y por qué es importante controlarlo?',
    opciones: ['Es el peso del eje mismo', 'Es el peso que soporta cada eje del camión y su exceso daña las carreteras', 'Es la presión de los neumáticos', 'Es el peso del motor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El peso por eje es la carga que soporta cada eje del vehículo. Los límites máximos por eje están regulados porque el exceso daña la infraestructura vial (pavimento y puentes). Un camión puede estar dentro del peso bruto máximo pero exceder el límite en un eje por mala distribución de la carga, lo que también constituye infracción.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1236,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Dónde se realiza el control de peso de los camiones en carreteras?',
    opciones: ['En cualquier estación de servicio', 'En plazas de pesaje o básculas camineras', 'En los peajes', 'No se realizan controles de peso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El control de peso se realiza en plazas de pesaje o básculas camineras ubicadas en puntos estratégicos de las carreteras. Los camiones están obligados a ingresar a estas plazas cuando la señalización lo indica. Eludir un control de peso constituye una infracción grave y puede significar la retención del vehículo.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1237,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué riesgos implica la fatiga para un conductor de camión?',
    opciones: ['Solo mayor consumo de combustible', 'Disminución de reflejos, microsueños, errores de juicio y pérdida de atención', 'Únicamente dolor de espalda', 'No implica riesgos significativos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La fatiga es una de las principales causas de accidentes en transporte de carga. Provoca disminución de reflejos, microsueños involuntarios, errores de juicio y pérdida de atención. Un conductor fatigado puede no percibir señales, cambios en la vía u otros vehículos. Por eso existen normas estrictas sobre horas de conducción y descanso.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1238,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué debe hacer un conductor de camión si detecta síntomas de fatiga durante un viaje?',
    opciones: ['Abrir las ventanas y subir la música', 'Detenerse en un lugar seguro y descansar antes de continuar', 'Tomar café y seguir conduciendo', 'Aumentar la velocidad para llegar antes'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante síntomas de fatiga como bostezos frecuentes, dificultad para mantener los ojos abiertos o desviaciones involuntarias del carril, el conductor debe detenerse en un lugar seguro y descansar al menos 20-30 minutos. Las soluciones temporales como café o música no eliminan la fatiga real y dan una falsa sensación de seguridad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1239,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sanciones enfrenta un conductor de carga que falsifica los registros del tacógrafo?',
    opciones: ['Solo una advertencia verbal', 'Multa, suspensión de licencia profesional y posibles sanciones penales', 'Solo una multa menor', 'No hay sanción específica'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Falsificar o manipular los registros del tacógrafo es una infracción gravísima que puede resultar en multas elevadas, suspensión de la licencia profesional y sanciones penales por falsificación de documentos. Las autoridades realizan fiscalizaciones periódicas y la tecnología digital hace cada vez más difícil la manipulación.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1240,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precaución debe tomar un camión al adelantar a otro vehículo?',
    opciones: ['Adelantar rápidamente cambiando bruscamente de pista', 'Considerar que necesita más tiempo y distancia para completar la maniobra por su mayor longitud', 'No necesita precauciones especiales', 'Tocar la bocina repetidamente mientras adelanta'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un camión necesita considerablemente más tiempo y distancia para adelantar debido a su mayor longitud y menor capacidad de aceleración. El conductor debe asegurarse de tener suficiente visibilidad, espacio y tiempo antes de iniciar la maniobra. Debe señalizar con anticipación y solo regresar a su carril cuando vea completamente el vehículo adelantado en el espejo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1241,
    categoria: 'Ley de Tránsito',
    pregunta: '¿En qué zonas está prohibido que un camión adelante a otro vehículo?',
    opciones: ['Solo en túneles', 'En curvas, túneles, puentes, cruces y zonas con línea continua', 'Solo en zonas escolares', 'No hay restricciones específicas para camiones'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los camiones tienen prohibido adelantar en curvas, túneles, puentes, cruces, pendientes pronunciadas y zonas demarcadas con línea continua. Dada la mayor longitud y tiempo requerido para la maniobra, el riesgo de colisión frontal es significativamente mayor. En muchas carreteras existen señales específicas de prohibición de adelantamiento para camiones.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1242,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué es el sistema de suspensión neumática en un camión y cuál es su ventaja?',
    opciones: ['Un sistema de aire acondicionado para la cabina', 'Un sistema que usa bolsas de aire en la suspensión para absorber irregularidades y proteger la carga', 'Un sistema de inflado automático de neumáticos', 'Un sistema de frenado auxiliar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La suspensión neumática utiliza bolsas de aire que absorben las irregularidades del camino, ofreciendo una conducción más suave y protegiendo mejor la carga. Permite ajustar la altura del chasis para facilitar operaciones de carga y descarga. Es especialmente importante para cargas frágiles y reduce el desgaste de la carretera.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1243,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el procedimiento correcto para cargar un camión en un muelle de carga?',
    opciones: ['Estacionar y comenzar a cargar inmediatamente', 'Asegurar el camión con cuñas, conectar el puente de carga y verificar que el freno de mano esté activado', 'Solo activar el freno de mano', 'Dejar el motor encendido y en neutro'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El procedimiento correcto incluye: posicionar el camión, activar el freno de mano, colocar cuñas en las ruedas, apagar el motor, conectar el puente de carga nivelado y verificar que la plataforma soporte el peso. Estas medidas previenen movimientos involuntarios del camión que pueden causar caídas de personal o carga.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1244,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo debe actuar un conductor de camión al circular por una zona de obras?',
    opciones: ['Mantener la velocidad normal y tocar la bocina', 'Reducir la velocidad, seguir la señalización temporal y estar atento a trabajadores y maquinaria', 'Detenerse y esperar a que terminen las obras', 'Buscar siempre una ruta alternativa'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En zonas de obras, el conductor debe reducir significativamente la velocidad, respetar la señalización temporal, mantener distancia de seguridad aumentada y estar muy atento a la presencia de trabajadores, maquinaria y cambios en el trazado de la vía. Las multas por exceso de velocidad en zonas de obras pueden duplicarse.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1245,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué tipo de extintor es obligatorio en un camión de carga?',
    opciones: ['Extintor de agua de 5 litros', 'Extintor de polvo químico seco de al menos 6 kg, tipo ABC', 'Extintor de CO2 de 2 kg', 'No es obligatorio llevar extintor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los camiones de carga deben portar al menos un extintor de polvo químico seco tipo ABC de mínimo 6 kg de capacidad. Para vehículos que transportan materiales peligrosos se exigen extintores adicionales y de mayor capacidad según el tipo de sustancia transportada. Debe estar accesible, señalizado y con su carga vigente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1246,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer un conductor si su carga comienza a desplazarse durante el viaje?',
    opciones: ['Continuar hasta el destino y arreglarla allí', 'Detenerse en un lugar seguro y reacomodar y asegurar la carga antes de continuar', 'Acelerar para que la inercia la reacomode', 'Llamar a la empresa y seguir conduciendo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si la carga se desplaza, el conductor debe detenerse lo antes posible en un lugar seguro (berma, área de servicio) y reacomodar y asegurar la carga antes de continuar. Continuar con carga desplazada puede causar desbalance, volcamiento o caída de la carga a la vía, poniendo en riesgo a todos los usuarios.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1247,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué requisitos debe cumplir un conductor para transportar materiales peligrosos?',
    opciones: ['Solo tener licencia clase A4', 'Licencia profesional vigente, curso especial de materiales peligrosos aprobado y certificación vigente', 'Solo un seguro especial', 'No hay requisitos adicionales'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para transportar materiales peligrosos se requiere licencia profesional vigente, haber aprobado un curso especial de transporte de sustancias peligrosas, contar con certificación vigente emitida por una entidad autorizada, y el vehículo debe cumplir requisitos técnicos especiales según la clase de sustancia a transportar.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1248,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué hacer en caso de derrame de la carga en la vía pública?',
    opciones: ['Recoger la carga personalmente sin importar qué sea', 'Señalizar la zona, alertar a otros conductores y contactar a emergencias si es material peligroso', 'Abandonar el lugar inmediatamente', 'Esperar a que otros conductores la recojan'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En caso de derrame, el conductor debe detenerse con seguridad, señalizar la zona con triángulos y balizas, alertar a otros conductores y contactar a Carabineros. Si se trata de materiales peligrosos, se debe llamar a Bomberos y no intentar recoger la sustancia sin el equipo adecuado. El conductor es responsable de los daños causados por su carga.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1249,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué es el sistema ABS en un camión y cómo funciona?',
    opciones: ['Un sistema de aire acondicionado', 'Un sistema antibloqueo de frenos que evita que las ruedas se bloqueen al frenar', 'Un sistema de alarma antirrobo', 'Un acelerador automático de velocidad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El ABS (Anti-lock Braking System) es un sistema que impide el bloqueo de las ruedas durante el frenado, permitiendo mantener la direccionalidad del vehículo. En camiones es especialmente importante porque un bloqueo de ruedas puede provocar el efecto tijera en vehículos articulados o la pérdida total de control.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1250,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el procedimiento correcto para enganchar un semirremolque a un tractocamión?',
    opciones: ['Simplemente retroceder y conectar', 'Verificar alineación, retroceder lentamente, asegurar la quinta rueda, conectar líneas de aire y eléctricas, verificar el enganche', 'Solo conectar las luces traseras', 'Empujar el semirremolque con otro vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El enganche correcto requiere: alinear el tractocamión con el semirremolque, retroceder lentamente hasta que el king pin entre en la quinta rueda, verificar el cierre del mecanismo, conectar las líneas de aire de frenos y la conexión eléctrica, subir las patas de apoyo y hacer una prueba de tracción para confirmar que el enganche es seguro.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1251,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué restricción de circulación aplica a camiones en feriados y fines de semana largos?',
    opciones: ['No hay restricciones', 'Restricción de circulación en rutas principales durante horarios de mayor flujo vehicular', 'Solo pueden circular de noche', 'Deben usar escolta policial'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Durante feriados y fines de semana largos, las autoridades pueden restringir la circulación de camiones en rutas principales durante horarios de mayor flujo vehicular para reducir la congestión y el riesgo de accidentes. Estas restricciones son informadas con anticipación y el incumplimiento acarrea multas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1252,
    categoria: 'Mecánica Básica',
    pregunta: '¿Qué indica una emisión excesiva de humo negro por el escape de un camión diésel?',
    opciones: ['Funcionamiento normal del motor', 'Combustión incompleta por problemas en inyectores, filtro de aire o turbo', 'Exceso de aceite en el motor', 'Neumáticos desgastados'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El humo negro excesivo indica una combustión incompleta del diésel, generalmente causada por inyectores en mal estado, filtro de aire obstruido, turbocompresor defectuoso o sobrecarga del motor. Además de contaminar el medio ambiente, un vehículo con emisiones excesivas puede ser rechazado en la revisión técnica y multado.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1253,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué efecto tiene la lluvia en la conducción de un camión cargado?',
    opciones: ['Ninguno significativo', 'Aumenta la distancia de frenado, reduce la visibilidad y puede provocar hidroplaneo', 'Solo reduce la visibilidad', 'Mejora la adherencia de los neumáticos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La lluvia afecta significativamente la conducción de un camión cargado: aumenta la distancia de frenado por la reducción de adherencia, disminuye la visibilidad, puede provocar hidroplaneo (acuaplaneo) y genera salpicaduras que reducen la visión de otros conductores. Se debe reducir la velocidad y aumentar la distancia de seguimiento.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1254,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué es el cabeceo en un camión y qué lo provoca?',
    opciones: ['Un movimiento lateral del volante', 'El balanceo longitudinal del vehículo causado por frenados y aceleraciones con carga', 'Un sonido del motor', 'Una falla en la transmisión'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El cabeceo es el movimiento de balanceo longitudinal (adelante-atrás) del camión, provocado por frenados bruscos y aceleraciones con carga. Este efecto se amplifica con cargas pesadas o mal aseguradas y puede hacer perder estabilidad al vehículo. Una conducción suave y progresiva minimiza este fenómeno.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1255,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué responsabilidad tiene el conductor si la carga cae del camión y causa un accidente?',
    opciones: ['Ninguna, es responsabilidad del cargador', 'Responsabilidad civil y penal por los daños causados', 'Solo responsabilidad civil', 'Solo debe pagar una multa de tránsito'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor tiene responsabilidad civil y penal si la carga cae del camión y causa daños o lesiones. Es su obligación verificar que la carga esté correctamente asegurada antes y durante el viaje. Puede enfrentar multas, indemnizaciones por daños, y cargos penales si hay lesiones o muerte.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1256,
    categoria: 'Mecánica Básica',
    pregunta: '¿Cuál es la función del turbocompresor en un motor diésel de camión?',
    opciones: ['Enfriar el motor', 'Aumentar la potencia del motor comprimiendo el aire de admisión', 'Reducir el ruido del escape', 'Filtrar las partículas del combustible'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El turbocompresor comprime el aire de admisión del motor, permitiendo introducir más aire y combustible en cada ciclo, lo que aumenta significativamente la potencia sin incrementar el tamaño del motor. Es esencial en camiones de carga para obtener la potencia necesaria para mover grandes pesos, especialmente en pendientes.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1257,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué elementos de protección personal debe usar un conductor durante la carga y descarga?',
    opciones: ['Ninguno especial', 'Casco, guantes, calzado de seguridad y chaleco reflectante según el tipo de carga', 'Solo guantes', 'Solo chaleco reflectante'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Durante operaciones de carga y descarga, el conductor debe usar los elementos de protección personal adecuados: casco, guantes de seguridad, calzado con punta de acero, chaleco reflectante y otros equipos según el tipo de carga. Para materiales peligrosos se requiere equipo adicional como mascarillas y trajes especiales.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1258,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo debe conducir un camión vacío comparado con uno cargado?',
    opciones: ['Exactamente igual', 'Con precaución adicional porque es más inestable, liviano y susceptible al viento', 'Puede ir más rápido ya que pesa menos', 'No hay diferencia en la conducción'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un camión vacío presenta riesgos diferentes: es más liviano y susceptible al viento lateral, tiene menos adherencia en los neumáticos traseros, puede rebotar más en irregularidades del camino y los frenos pueden bloquearse más fácilmente. El conductor debe adaptar su conducción a estas condiciones diferentes.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a4'],
  },
  {
    id: 1259,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué es la carta de porte y cuándo es necesaria?',
    opciones: ['Un permiso de conducir especial', 'Un documento que acredita el contrato de transporte de mercancías', 'Una tarjeta de crédito para peajes', 'Un seguro de la carga'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La carta de porte es un documento que acredita la existencia de un contrato de transporte de mercancías por carretera. Contiene datos del remitente, destinatario, transportista, descripción de la mercancía, peso, origen y destino. Es obligatoria en el transporte comercial de carga y debe acompañar al conductor durante todo el viaje.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a4'],
  },
];
