import type { Question } from './questionsData';

export const questionsA2: Question[] = [
  // =============================================
  // LEY DE TRÁNSITO (18 preguntas) - IDs 1100-1117
  // =============================================
  {
    id: 1100,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuántos pasajeros puede transportar un vehículo con licencia Clase A2?',
    opciones: ['Hasta 9 pasajeros', 'De 10 a 17 pasajeros', 'De 18 a 30 pasajeros', 'Más de 30 pasajeros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La licencia Clase A2 habilita para conducir vehículos de transporte de pasajeros con capacidad de 10 a 17 asientos, como minibuses. Transportar más pasajeros de los permitidos constituye una infracción gravísima y compromete la seguridad de todos los ocupantes.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1101,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué edad mínima se requiere para obtener la licencia profesional Clase A2?',
    opciones: ['18 años', '20 años', '21 años', '25 años'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Para obtener la licencia profesional Clase A2 se requiere tener al menos 20 años de edad, además de poseer licencia Clase B con un mínimo de 2 años de antigüedad. También se debe aprobar un curso en una escuela de conductores profesionales autorizada.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1102,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cada cuánto tiempo debe realizarse la revisión técnica de un minibús de transporte de pasajeros?',
    opciones: ['Cada 2 años', 'Cada año', 'Cada 6 meses', 'Cada 3 meses'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los vehículos de transporte público de pasajeros deben someterse a revisión técnica cada 6 meses, a diferencia de los vehículos particulares que la realizan anualmente. Esta mayor frecuencia se justifica por el uso intensivo y la responsabilidad de transportar personas.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1103,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la tolerancia de alcohol permitida para un conductor profesional Clase A2?',
    opciones: ['0,3 g/l', '0,1 g/l', '0,0 g/l (tolerancia cero)', '0,5 g/l'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Los conductores profesionales tienen tolerancia cero de alcohol (0,0 g/l). Cualquier nivel detectable de alcohol constituye infracción gravísima con suspensión inmediata de la licencia profesional, dada la responsabilidad de transportar pasajeros.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1104,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué seguro adicional debe tener un minibús de transporte de pasajeros además del SOAP?',
    opciones: ['Solo el SOAP es suficiente', 'Seguro de responsabilidad civil por daños a terceros y pasajeros', 'Seguro contra robo únicamente', 'Seguro de vida del conductor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los vehículos de transporte de pasajeros deben contar con un seguro de responsabilidad civil que cubra daños a terceros y a los pasajeros transportados, además del SOAP obligatorio. Este seguro protege a los pasajeros ante cualquier eventualidad durante el trayecto.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1105,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué documento debe portar siempre un conductor de transporte de pasajeros además de los documentos habituales?',
    opciones: ['Carné de salud', 'Tarjeta nacional de transporte público y certificado de antecedentes', 'Pasaporte vigente', 'Certificado de escolaridad'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor de transporte de pasajeros debe portar, además de licencia, permiso de circulación, SOAP y revisión técnica, la tarjeta nacional de transporte público y certificado de antecedentes penales vigente. La ausencia de estos documentos puede significar multas y la retención del vehículo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1106,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Está permitido que un pasajero viaje de pie en un minibús Clase A2?',
    opciones: ['Sí, siempre que haya espacio', 'Sí, solo en trayectos urbanos cortos', 'No, todos los pasajeros deben ir sentados con cinturón', 'Solo si el minibús tiene barras de sujeción'],
    respuestaCorrecta: 2,
    explicacionTexto: 'En los minibuses de transporte interurbano o turístico, todos los pasajeros deben viajar sentados y con cinturón de seguridad. No se permite transportar pasajeros de pie. Cada asiento debe contar con cinturón de seguridad en buen estado y el conductor debe verificar su uso.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1107,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué velocidad máxima debe respetar un minibús de transporte de pasajeros en autopista?',
    opciones: ['120 km/h', '100 km/h', '90 km/h', '80 km/h'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los minibuses de transporte de pasajeros tienen una velocidad máxima de 100 km/h en autopistas, inferior a los 120 km/h permitidos para vehículos livianos. Esta restricción se debe a la mayor responsabilidad que implica transportar personas y las características de frenado de estos vehículos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1108,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sanción enfrenta un conductor Clase A2 que transporta más pasajeros de los permitidos?',
    opciones: ['Amonestación verbal', 'Infracción leve', 'Infracción grave con posible suspensión de licencia profesional', 'Infracción gravísima con cancelación definitiva de licencia'],
    respuestaCorrecta: 2,
    explicacionTexto: 'Transportar más pasajeros de los autorizados constituye una infracción grave que puede derivar en la suspensión de la licencia profesional. Además, el exceso de pasajeros compromete la estabilidad del vehículo, aumenta la distancia de frenado y reduce la capacidad de maniobra ante emergencias.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1109,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué requisito de salud especial debe cumplir un conductor profesional Clase A2?',
    opciones: ['No se requiere examen de salud especial', 'Certificado de salud compatible con transporte de personas, incluyendo examen psicotécnico', 'Solo un examen de vista', 'Solo un examen auditivo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los conductores profesionales Clase A2 deben contar con un certificado de salud que acredite aptitud física y mental para el transporte de personas. Incluye exámenes de visión, audición, coordinación motora y evaluación psicotécnica. Este certificado debe renovarse periódicamente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1110,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué obligación tiene el conductor respecto a personas con movilidad reducida que desean abordar el minibús?',
    opciones: ['No tiene obligación especial', 'Debe facilitar el acceso y dar tiempo suficiente para abordar y descender', 'Puede negarse si no hay rampas', 'Solo debe ayudar si se lo piden expresamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La Ley 20.422 sobre igualdad de oportunidades e inclusión social establece que los conductores de transporte de pasajeros deben facilitar el acceso a personas con discapacidad o movilidad reducida, dando tiempo suficiente para abordar y descender del vehículo de manera segura.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1111,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Es obligatorio que el minibús cuente con extintor de incendios?',
    opciones: ['No, es opcional', 'Sí, al menos uno de 2 kg en lugar accesible', 'Solo en viajes interurbanos', 'Solo si transporta más de 15 pasajeros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Todo vehículo de transporte de pasajeros debe llevar al menos un extintor de incendios de mínimo 2 kg, en lugar visible y de fácil acceso. El conductor debe verificar que esté cargado y vigente. Además, debe conocer su funcionamiento para actuar rápidamente en caso de emergencia.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1112,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué elementos de seguridad adicionales debe tener un minibús de transporte de pasajeros?',
    opciones: ['Solo cinturones de seguridad', 'Extintor, botiquín de primeros auxilios, martillo rompecristales y salidas de emergencia señalizadas', 'Solo extintor y triángulo', 'Los mismos que un vehículo particular'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un minibús de transporte de pasajeros debe contar con extintor vigente, botiquín de primeros auxilios completo, martillo rompecristales, salidas de emergencia claramente señalizadas, cinturones de seguridad en todos los asientos y triángulos de seguridad. Estos elementos son verificados en la revisión técnica.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1113,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Puede un conductor Clase A2 negarse a transportar a un pasajero por motivos de discriminación?',
    opciones: ['Sí, tiene derecho a elegir sus pasajeros', 'No, constituye una falta a la Ley Antidiscriminación', 'Solo si el pasajero está en estado de ebriedad', 'Solo en servicios privados'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La Ley 20.609 (Ley Zamudio) prohíbe la discriminación arbitraria en los servicios de transporte. Un conductor no puede negarse a transportar a un pasajero por razones de raza, sexo, orientación sexual, religión, apariencia u otra condición. Solo puede negarse si el pasajero pone en riesgo la seguridad del servicio.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1114,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué debe hacer el conductor si un pasajero no usa el cinturón de seguridad?',
    opciones: ['No es su responsabilidad', 'Debe exigir su uso antes de iniciar la marcha y puede negarse a continuar', 'Solo debe sugerirlo', 'Debe informar a Carabineros al final del viaje'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor profesional es responsable de que todos los pasajeros usen cinturón de seguridad. Debe verificar su uso antes de iniciar la marcha y puede negarse a continuar el viaje si algún pasajero no cumple. La responsabilidad legal recae en el conductor ante una fiscalización.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1115,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Cuál es la antigüedad máxima permitida para un minibús de transporte público de pasajeros?',
    opciones: ['Sin límite de antigüedad', 'Depende de la región y el tipo de servicio, generalmente entre 10 y 15 años', '5 años', '20 años'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La antigüedad máxima de los vehículos de transporte público de pasajeros varía según la región y el tipo de servicio, pero generalmente se establece entre 10 y 15 años. Esta regulación busca garantizar condiciones mínimas de seguridad y confort para los pasajeros.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1116,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué sucede con la licencia Clase A2 si el conductor comete una infracción gravísima?',
    opciones: ['Se suspende solo la licencia Clase B', 'Se puede suspender o cancelar la licencia profesional Clase A2', 'Solo recibe una multa económica', 'No afecta a la licencia profesional'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Una infracción gravísima puede resultar en la suspensión o cancelación de la licencia profesional Clase A2, además de las multas correspondientes. La cancelación implica que el conductor no podrá ejercer como profesional hasta obtener una nueva licencia, cumpliendo todos los requisitos desde el principio.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1117,
    categoria: 'Ley de Tránsito',
    pregunta: '¿Qué normativa regula las condiciones laborales de los conductores profesionales de transporte de pasajeros?',
    opciones: ['Solo el Código del Trabajo general', 'El Código del Trabajo con disposiciones especiales para conductores profesionales', 'No existe regulación específica', 'Solo las normas del Ministerio de Transportes'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El Código del Trabajo contiene disposiciones especiales para conductores profesionales de transporte de pasajeros, regulando jornadas máximas, tiempos de descanso obligatorios, horas de conducción continua y descansos entre turnos. Estas normas buscan prevenir la fatiga al volante.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },

  // =============================================
  // CONDUCCIÓN SEGURA (18 preguntas) - IDs 1118-1135
  // =============================================
  {
    id: 1118,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la distancia de seguimiento recomendada para un minibús cargado con pasajeros?',
    opciones: ['La misma que un vehículo liviano', 'Mayor que un vehículo liviano, al menos 4 segundos', '2 segundos como cualquier vehículo', '1 segundo por cada pasajero'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Un minibús con pasajeros tiene mayor peso y necesita más distancia de frenado. Se recomienda mantener al menos 4 segundos de distancia con el vehículo que lo precede, aumentando esta distancia en condiciones adversas como lluvia, niebla o pavimento mojado.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1119,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe realizar las frenadas un conductor de minibús con pasajeros?',
    opciones: ['Frenadas bruscas para mayor seguridad', 'Frenadas suaves y progresivas para evitar que los pasajeros se golpeen', 'Igual que en un vehículo liviano', 'Solo usar freno de motor'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor de un minibús debe realizar frenadas suaves y progresivas, anticipándose a las situaciones. Las frenadas bruscas pueden causar lesiones a los pasajeros, especialmente a personas mayores, niños o personas con movilidad reducida. La conducción anticipativa es fundamental.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1120,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precauciones debe tomar el conductor al detenerse para que suban o bajen pasajeros?',
    opciones: ['Detenerse en cualquier lugar conveniente', 'Detenerse en paradero autorizado, activar luces intermitentes y esperar que los pasajeros estén seguros', 'Solo reducir velocidad sin detenerse completamente', 'Detenerse en la pista de circulación'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor debe detenerse solo en paraderos autorizados, activar las luces intermitentes, abrir las puertas cuando el vehículo esté completamente detenido y no reiniciar la marcha hasta que todos los pasajeros hayan subido o bajado y las puertas estén cerradas. Debe verificar por los espejos que no haya pasajeros en la zona de riesgo.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1121,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe verificar el conductor antes de iniciar cada jornada de servicio?',
    opciones: ['Solo el nivel de combustible', 'Estado de frenos, luces, neumáticos, espejos, puertas, extintor y documentación', 'Solo que el motor encienda correctamente', 'Solo la limpieza interior del vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de cada jornada, el conductor debe realizar una inspección completa: verificar frenos, luces, neumáticos, nivel de fluidos, espejos retrovisores, funcionamiento de puertas, estado del extintor, botiquín, cinturones de seguridad y toda la documentación. Esta revisión previene fallas mecánicas durante el servicio.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1122,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe actuar el conductor si detecta humo o principio de incendio en el minibús?',
    opciones: ['Seguir conduciendo hasta el próximo paradero', 'Detenerse inmediatamente en lugar seguro, evacuar a los pasajeros y usar el extintor', 'Abrir las ventanas y seguir conduciendo', 'Llamar a bomberos sin detenerse'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante humo o principio de incendio, el conductor debe detenerse de inmediato en un lugar seguro, apagar el motor, evacuar a todos los pasajeros ordenadamente por las salidas de emergencia, usar el extintor si es seguro hacerlo y llamar a bomberos. La prioridad absoluta es la vida de los pasajeros.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1123,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuántas horas máximas de conducción continua puede realizar un conductor de transporte de pasajeros?',
    opciones: ['8 horas sin parar', '5 horas, luego debe descansar al menos 2 horas', 'No hay límite si se siente bien', '10 horas con pausas de 15 minutos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los conductores de transporte de pasajeros no pueden conducir más de 5 horas continuas, debiendo realizar un descanso mínimo de 2 horas antes de continuar. La jornada total no debe exceder las horas establecidas por ley. La fatiga es una de las principales causas de accidentes en transporte de pasajeros.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1124,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer el conductor si un pasajero se siente mal durante el viaje?',
    opciones: ['Continuar hasta el destino final', 'Detenerse en lugar seguro, prestar primeros auxilios básicos y solicitar asistencia médica', 'Acelerar para llegar más rápido al hospital', 'Pedirle al pasajero que se baje en el próximo paradero'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si un pasajero se siente mal, el conductor debe detenerse en un lugar seguro, evaluar la situación, prestar primeros auxilios básicos con el botiquín del vehículo y llamar a servicios de emergencia si es necesario. La salud de los pasajeros es responsabilidad del conductor durante el trayecto.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1125,
    categoria: 'Conducción Segura',
    pregunta: '¿Por qué es especialmente peligroso tomar curvas a alta velocidad en un minibús?',
    opciones: ['No es más peligroso que en un automóvil', 'El centro de gravedad más alto aumenta el riesgo de volcamiento', 'Solo es peligroso si llueve', 'Solo si el minibús está vacío'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los minibuses tienen un centro de gravedad más alto que los automóviles, lo que los hace más propensos al volcamiento en curvas a alta velocidad. Este riesgo aumenta con pasajeros de pie o con carga mal distribuida. El conductor debe reducir significativamente la velocidad antes de entrar a una curva.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1126,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué precaución especial debe tener un conductor de minibús al circular por zonas escolares?',
    opciones: ['No hay precauciones especiales', 'Reducir velocidad a máximo 30 km/h, estar atento a niños y detenerse si hay cruce escolar', 'Solo tocar la bocina para advertir', 'Circular normalmente si no hay semáforo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En zonas escolares, el conductor de minibús debe reducir la velocidad a máximo 30 km/h, estar extremadamente atento a la presencia de niños que pueden cruzar de manera imprevista, y detenerse completamente cuando un cruce escolar esté activo. Los niños son usuarios especialmente vulnerables.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1127,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe actuar el conductor ante condiciones de visibilidad reducida como neblina densa?',
    opciones: ['Usar luces altas para ver mejor', 'Reducir velocidad, usar luces bajas y neblineros, aumentar distancia de seguimiento', 'Detenerse y esperar que pase la neblina', 'Seguir al vehículo de adelante a corta distancia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Con neblina densa, el conductor debe reducir significativamente la velocidad, encender luces bajas y neblineros (nunca luces altas que producen reflejo), aumentar la distancia de seguimiento y, si la visibilidad es extremadamente baja, detenerse en lugar seguro fuera de la calzada. La seguridad de los pasajeros es prioritaria.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1128,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer el conductor si las puertas del minibús no cierran correctamente?',
    opciones: ['Conducir con precaución hasta el taller', 'No iniciar la marcha hasta que las puertas funcionen correctamente', 'Pedir a un pasajero que sujete la puerta', 'Amarrar la puerta con una cuerda'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor no debe iniciar la marcha si las puertas no cierran correctamente, ya que un pasajero podría caer del vehículo en movimiento. Las puertas son un elemento de seguridad crítico. El vehículo debe ser reparado antes de continuar el servicio.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1129,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es la forma correcta de utilizar los espejos retrovisores en un minibús?',
    opciones: ['Solo mirar el espejo central', 'Revisar constantemente los espejos laterales, central y de ángulo muerto', 'Solo mirar los espejos al estacionar', 'Los espejos no son necesarios si hay cámara trasera'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor de minibús debe revisar constantemente los espejos retrovisores laterales, el central interior y los de ángulo muerto. Es especialmente importante verificar los espejos antes de cambiar de pista, al detenerse y antes de reanudar la marcha, para detectar pasajeros u otros usuarios cerca del vehículo.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1130,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué factor aumenta significativamente la distancia de frenado de un minibús?',
    opciones: ['El color del vehículo', 'El peso total del vehículo con pasajeros y las condiciones del pavimento', 'La marca del minibús', 'La hora del día'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La distancia de frenado aumenta con el peso total del vehículo (más pasajeros = más peso = más distancia), el pavimento mojado o en mal estado, la velocidad, el estado de los neumáticos y frenos, y la pendiente de la vía. Un minibús lleno puede requerir hasta el doble de distancia de frenado que uno vacío.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1131,
    categoria: 'Conducción Segura',
    pregunta: '¿Cómo debe actuar el conductor al descender una pendiente pronunciada con el minibús cargado?',
    opciones: ['Usar solo el freno de pie continuamente', 'Usar el freno de motor (marcha baja) y complementar con freno de servicio', 'Poner el vehículo en neutro para ahorrar combustible', 'Frenar solo al final de la pendiente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Al descender pendientes pronunciadas, se debe usar el freno de motor engranando una marcha baja y complementar con el freno de servicio de forma intermitente. Usar el freno de pie continuamente puede sobrecalentarlo y provocar su falla total (fading), situación extremadamente peligrosa con pasajeros a bordo.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1132,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué acción debe tomar el conductor si un pasajero se comporta de manera agresiva o pone en riesgo la seguridad?',
    opciones: ['Ignorar la situación y seguir conduciendo', 'Detenerse en lugar seguro y solicitar apoyo de Carabineros', 'Discutir con el pasajero mientras conduce', 'Expulsar al pasajero en cualquier lugar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si un pasajero pone en riesgo la seguridad, el conductor debe detenerse en un lugar seguro, mantener la calma, no confrontar al pasajero y solicitar apoyo de Carabineros. Nunca debe intentar resolver la situación mientras conduce, ya que la distracción puede causar un accidente.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1133,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué verificación debe hacer el conductor antes de retroceder con el minibús?',
    opciones: ['Solo mirar por el espejo retrovisor central', 'Verificar que no haya personas ni obstáculos detrás, usando espejos y bajándose si es necesario', 'Tocar la bocina y retroceder', 'Pedir a un pasajero que mire por la ventana trasera'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Antes de retroceder, el conductor debe verificar completamente la zona trasera usando todos los espejos y, si es necesario, bajarse del vehículo para comprobar que no haya personas, niños u obstáculos detrás. Los puntos ciegos de un minibús son considerablemente mayores que los de un automóvil.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1134,
    categoria: 'Conducción Segura',
    pregunta: '¿Cuál es el riesgo principal de conducir un minibús con neumáticos desgastados?',
    opciones: ['Mayor consumo de combustible únicamente', 'Pérdida de adherencia, mayor distancia de frenado y riesgo de aquaplaning', 'Solo afecta la comodidad del viaje', 'No hay riesgo significativo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Los neumáticos desgastados reducen drásticamente la adherencia al pavimento, aumentan la distancia de frenado y elevan el riesgo de aquaplaning en pavimento mojado. En un minibús con pasajeros, esto multiplica el peligro. La profundidad mínima legal del dibujo del neumático es de 1,6 mm.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1135,
    categoria: 'Conducción Segura',
    pregunta: '¿Qué debe hacer el conductor si el minibús sufre una falla mecánica grave durante el recorrido?',
    opciones: ['Continuar hasta el destino a baja velocidad', 'Detenerse de forma segura, evacuar a los pasajeros si es necesario y solicitar asistencia', 'Intentar reparar la falla mientras los pasajeros esperan dentro', 'Pedir a los pasajeros que empujen el vehículo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante una falla mecánica grave, el conductor debe detenerse en un lugar seguro fuera de la calzada, activar luces de emergencia, colocar triángulos de seguridad, evaluar si es necesario evacuar a los pasajeros y solicitar asistencia mecánica. Nunca debe intentar continuar si la falla compromete la seguridad.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },

  // =============================================
  // CONDUCCIÓN DEFENSIVA (14 preguntas) - IDs 1136-1149
  // =============================================
  {
    id: 1136,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué es la conducción defensiva aplicada al transporte de pasajeros?',
    opciones: ['Conducir lo más rápido posible para evitar peligros', 'Anticipar situaciones de riesgo y actuar preventivamente para proteger a los pasajeros', 'Conducir siempre por el carril izquierdo', 'Usar la bocina frecuentemente para alertar a otros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La conducción defensiva en transporte de pasajeros implica anticipar posibles situaciones de riesgo, mantener distancias seguras, observar constantemente el entorno, respetar los límites de velocidad y tomar decisiones que prioricen la seguridad de los pasajeros por sobre la puntualidad del servicio.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1137,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo debe anticiparse el conductor de minibús ante un cruce con semáforo en ámbar?',
    opciones: ['Acelerar para pasar antes que cambie a rojo', 'Frenar progresivamente y detenerse, considerando el peso del vehículo y la seguridad de los pasajeros', 'Mantener la velocidad si no hay otros vehículos', 'Tocar la bocina y pasar rápidamente'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante un semáforo en ámbar, el conductor de minibús debe frenar progresivamente considerando que el mayor peso del vehículo requiere más distancia de frenado. Una frenada brusca podría lesionar a los pasajeros. La conducción anticipativa permite prever el cambio de luz y frenar con suavidad.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1138,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué técnica de observación debe usar constantemente el conductor de minibús?',
    opciones: ['Mirar solo al frente', 'Exploración visual 360°: espejos cada 5-8 segundos, mirada lejana y cercana alternada', 'Solo mirar cuando va a cambiar de pista', 'Confiar solo en la cámara de retroceso'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor de minibús debe mantener una exploración visual constante de 360°: revisar espejos retrovisores cada 5-8 segundos, alternar la mirada entre el horizonte lejano y el entorno cercano, verificar puntos ciegos antes de maniobrar y estar atento a peatones, ciclistas y otros vehículos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1139,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es la regla de los "2 segundos" adaptada para un minibús con pasajeros?',
    opciones: ['Mantener 2 segundos de distancia siempre', 'Duplicar o triplicar la distancia estándar de 2 segundos según peso y condiciones', 'No aplica para minibuses', 'Solo aplica en autopistas'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La regla de los 2 segundos para vehículos livianos debe duplicarse o triplicarse para un minibús con pasajeros. Esto significa mantener al menos 4-6 segundos de distancia con el vehículo delantero. En condiciones adversas (lluvia, noche, curvas), esta distancia debe aumentarse aún más.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1140,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué debe hacer el conductor si un vehículo lo adelanta de forma peligrosa mientras transporta pasajeros?',
    opciones: ['Acelerar para no dejarse adelantar', 'Reducir velocidad, mantener la calma y dar espacio al vehículo que adelanta', 'Tocar la bocina prolongadamente', 'Realizar una maniobra evasiva brusca'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante un adelantamiento peligroso, el conductor debe reducir velocidad para dar espacio al vehículo que adelanta, mantener la calma y no realizar maniobras bruscas que pongan en riesgo a los pasajeros. La prioridad siempre es la seguridad de las personas transportadas por sobre la confrontación vial.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1141,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo debe actuar el conductor de minibús al aproximarse a un paso peatonal con personas esperando?',
    opciones: ['Pasar rápido si no están cruzando', 'Reducir velocidad, estar preparado para detenerse y ceder el paso a los peatones', 'Tocar la bocina para que los peatones esperen', 'Cambiar de pista para evitar el cruce'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor defensivo debe reducir la velocidad al aproximarse a un paso peatonal, cubrir el freno con el pie, estar preparado para detenerse completamente y ceder el paso a los peatones. Los peatones siempre tienen prioridad en los cruces demarcados, especialmente cuando un vehículo grande se aproxima.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1142,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué estrategia defensiva debe aplicar el conductor al circular por zonas con muchos ciclistas?',
    opciones: ['Tocar la bocina para que se aparten', 'Mantener distancia lateral de 1,5 m, reducir velocidad y anticipar movimientos imprevistos', 'Circular pegado al ciclista para que se mueva a la vereda', 'Adelantar inmediatamente sin importar las condiciones'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En zonas con ciclistas, el conductor debe mantener al menos 1,5 metros de distancia lateral, reducir la velocidad y anticipar que los ciclistas pueden hacer movimientos imprevistos como esquivar baches o abrirse. Un minibús genera corrientes de aire que pueden desestabilizar a un ciclista.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1143,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Por qué un conductor de minibús debe evitar las distracciones al volante más que un conductor particular?',
    opciones: ['No hay diferencia en el nivel de riesgo', 'Porque es responsable de la vida de múltiples pasajeros y maneja un vehículo más difícil de controlar', 'Porque los minibuses son más lentos', 'Solo para cumplir con la normativa'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El conductor de minibús tiene la responsabilidad de múltiples vidas humanas. Además, un vehículo más grande requiere mayor tiempo de reacción y distancia de frenado. Una distracción de apenas 2 segundos a 60 km/h significa recorrer 33 metros sin control, lo que en un minibús con pasajeros puede ser catastrófico.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1144,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es la mejor estrategia al conducir un minibús bajo lluvia intensa?',
    opciones: ['Mantener la velocidad habitual con luces encendidas', 'Reducir velocidad un 30-40%, aumentar distancia, usar luces bajas y neblineros', 'Detenerse hasta que pare la lluvia', 'Conducir por la berma para evitar el agua'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Bajo lluvia intensa, el conductor debe reducir la velocidad entre un 30% y 40%, aumentar significativamente la distancia de seguimiento, encender luces bajas y neblineros, evitar frenadas bruscas y estar atento al aquaplaning. Si la visibilidad es muy reducida, es preferible detenerse en un lugar seguro.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1145,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué debe considerar el conductor al planificar una ruta de transporte de pasajeros?',
    opciones: ['Solo la ruta más corta', 'Condiciones de la vía, clima, horarios de tráfico, zonas de riesgo y paraderos seguros', 'Solo el consumo de combustible', 'Solo las preferencias de los pasajeros'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La planificación de ruta debe considerar las condiciones del pavimento, pronóstico meteorológico, horarios de mayor congestión, zonas con obras o riesgos conocidos, ubicación de paraderos seguros y alternativas en caso de contingencias. Una buena planificación es parte fundamental de la conducción defensiva.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1146,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cómo debe reaccionar el conductor si un neumático revienta mientras transporta pasajeros?',
    opciones: ['Frenar bruscamente', 'Sujetar firmemente el volante, no frenar de golpe, reducir velocidad gradualmente y detenerse en lugar seguro', 'Soltar el volante para que el vehículo se alinee solo', 'Acelerar para mantener el control'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si un neumático revienta, el conductor debe sujetar firmemente el volante con ambas manos, no frenar bruscamente, levantar el pie del acelerador para reducir velocidad gradualmente, activar luces de emergencia y dirigirse hacia la berma o lugar seguro. Una frenada brusca puede provocar la pérdida total de control.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1147,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Por qué es importante que el conductor de minibús descanse adecuadamente antes de conducir?',
    opciones: ['Solo es una recomendación, no es importante', 'La fatiga reduce los tiempos de reacción y la capacidad de juicio, poniendo en riesgo a todos los pasajeros', 'Solo importa en viajes largos', 'No afecta la capacidad de conducción'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La fatiga reduce significativamente los tiempos de reacción, la capacidad de concentración y el juicio del conductor. Un conductor fatigado es tan peligroso como uno bajo los efectos del alcohol. Dado que transporta pasajeros, el riesgo se multiplica. Se recomienda dormir al menos 7-8 horas antes de conducir.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1148,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Qué precaución especial debe tener al conducir un minibús de noche?',
    opciones: ['Usar siempre luces altas', 'Reducir velocidad, aumentar distancia de seguimiento y estar especialmente atento a peatones', 'Conducir a la misma velocidad que de día', 'Confiar solo en el alumbrado público'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La conducción nocturna reduce la visibilidad y la percepción de distancias. El conductor debe reducir la velocidad, aumentar la distancia de seguimiento, usar correctamente las luces y estar especialmente atento a peatones y ciclistas que pueden ser menos visibles. La fatiga nocturna también es un factor de riesgo importante.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1149,
    categoria: 'Conducción Defensiva',
    pregunta: '¿Cuál es la importancia de la comunicación con los pasajeros durante situaciones de emergencia?',
    opciones: ['No es necesario comunicarse con los pasajeros', 'Informar con calma las instrucciones de evacuación y seguridad para evitar el pánico', 'Gritar para que obedezcan rápidamente', 'Dejar que los pasajeros se organicen solos'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Durante una emergencia, el conductor debe comunicarse con calma y claridad, dando instrucciones precisas sobre las salidas de emergencia, el uso de martillo rompecristales y el punto de reunión seguro. Mantener la calma evita el pánico colectivo, que puede causar más víctimas que la emergencia misma.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },

  // =============================================
  // PRIMEROS AUXILIOS (10 preguntas) - IDs 1150-1159
  // =============================================
  {
    id: 1150,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué elementos mínimos debe contener el botiquín de un minibús de transporte de pasajeros?',
    opciones: ['Solo curitas y alcohol', 'Gasas, vendas, tijeras, guantes desechables, antiséptico, mascarilla RCP y manual de primeros auxilios', 'Solo medicamentos para el dolor', 'No es obligatorio tener botiquín'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El botiquín debe contener gasas estériles, vendas de distintos tamaños, tijeras, cinta adhesiva, guantes desechables, solución antiséptica, mascarilla para RCP, parches oculares, férulas improvisables y un manual básico de primeros auxilios. Debe verificarse periódicamente que los insumos estén vigentes y completos.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1151,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Cuál es la primera acción del conductor si un pasajero sufre un desmayo durante el viaje?',
    opciones: ['Seguir conduciendo hasta el hospital más cercano', 'Detener el vehículo, acostar al pasajero, elevar sus piernas y asegurar ventilación', 'Darle agua inmediatamente', 'Sacudir al pasajero para que despierte'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante un desmayo, el conductor debe detener el vehículo de forma segura, acostar al pasajero boca arriba, elevar sus piernas para favorecer el retorno venoso, aflojar prendas ajustadas y asegurar ventilación. No se debe dar líquidos a una persona inconsciente. Si no recupera la conciencia, llamar a servicios de emergencia.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1152,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Cómo debe actuar el conductor si un pasajero presenta síntomas de ataque cardíaco?',
    opciones: ['Darle aspirina y seguir el viaje', 'Detener el vehículo, llamar al 131, sentar al pasajero cómodamente y estar preparado para RCP', 'Conducir rápidamente al hospital más cercano', 'Esperar a que se le pase'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante síntomas de ataque cardíaco (dolor de pecho, dificultad respiratoria, sudoración), el conductor debe detenerse inmediatamente, llamar al 131 (SAMU), sentar al pasajero en posición cómoda, aflojar prendas ajustadas y estar preparado para realizar RCP si pierde la conciencia y deja de respirar.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1153,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué debe hacer el conductor si un pasajero sufre una crisis epiléptica durante el viaje?',
    opciones: ['Sujetarlo firmemente para que no se mueva', 'Detener el vehículo, proteger al pasajero de golpes, no introducir nada en su boca y esperar que pase la crisis', 'Darle agua', 'Sacudirlo para que despierte'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Durante una crisis epiléptica, el conductor debe detener el vehículo, proteger al pasajero de golpes apartando objetos cercanos, colocar algo suave bajo su cabeza, NO introducir nada en su boca, NO sujetarlo y cronometrar la duración. Si dura más de 5 minutos, llamar a emergencias.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1154,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Cuál es el número de emergencia del SAMU en Chile?',
    opciones: ['911', '131', '132', '133'],
    respuestaCorrecta: 1,
    explicacionTexto: 'El SAMU (Servicio de Atención Médica de Urgencia) se contacta al 131. También es útil conocer: 132 para Bomberos y 133 para Carabineros. Un conductor de transporte de pasajeros debe tener estos números siempre accesibles para actuar rápidamente ante emergencias.',
    urlAudio: null,
    dificultad: 'facil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1155,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Cómo debe actuar el conductor si ocurre un accidente y hay pasajeros con heridas sangrantes?',
    opciones: ['Aplicar torniquete inmediatamente', 'Usar guantes, aplicar presión directa con gasas sobre la herida y llamar a emergencias', 'Lavar la herida con agua', 'No tocar al herido y esperar a la ambulancia'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Ante heridas sangrantes, el conductor debe colocarse guantes desechables del botiquín, aplicar presión directa sobre la herida con gasas estériles, elevar la zona afectada si es posible y llamar a servicios de emergencia. No se deben retirar objetos clavados ni aplicar torniquetes salvo que sea estrictamente necesario.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1156,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué es la posición lateral de seguridad y cuándo aplicarla a un pasajero?',
    opciones: ['Sentar al pasajero erguido', 'Acostar al pasajero de costado cuando está inconsciente pero respira, para evitar atragantamiento', 'Acostar al pasajero boca abajo', 'Mantener al pasajero de pie'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La posición lateral de seguridad consiste en acostar a la persona inconsciente pero que respira de costado, con la pierna superior flexionada para estabilidad. Esto evita que la lengua obstruya la vía aérea y que pueda ahogarse con vómito. Es fundamental para el conductor conocer esta técnica.',
    urlAudio: null,
    dificultad: 'media',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1157,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué debe hacer el conductor si un pasajero se atraganta y no puede respirar?',
    opciones: ['Darle golpes en la espalda al azar', 'Aplicar la maniobra de Heimlich: compresiones abdominales rápidas desde atrás', 'Darle agua para tragar', 'Esperar a que se le pase solo'],
    respuestaCorrecta: 1,
    explicacionTexto: 'Si un pasajero se atraganta y no puede respirar ni toser, se debe aplicar la maniobra de Heimlich: colocarse detrás del pasajero, rodear su abdomen con los brazos y realizar compresiones rápidas y firmes hacia arriba. Si pierde la conciencia, iniciar RCP y llamar al 131.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1158,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Cómo debe organizarse la evacuación de un minibús después de un accidente?',
    opciones: ['Todos deben salir por la puerta principal', 'Evacuar ordenadamente usando todas las salidas disponibles, priorizando heridos, niños y adultos mayores', 'Esperar instrucciones de Carabineros', 'Cada pasajero debe buscar su propia salida'],
    respuestaCorrecta: 1,
    explicacionTexto: 'La evacuación debe ser ordenada, usando la puerta principal y las salidas de emergencia. Se debe priorizar la evacuación de heridos, niños, adultos mayores y personas con movilidad reducida. El conductor debe dirigir la evacuación con calma, verificar que no quede nadie dentro y reunir a los pasajeros en un punto seguro.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
  {
    id: 1159,
    categoria: 'Primeros Auxilios',
    pregunta: '¿Qué protocolo debe seguir el conductor si el minibús se detiene en un túnel por emergencia?',
    opciones: ['Esperar dentro del vehículo con el motor encendido', 'Apagar el motor, no usar el sistema de ventilación, evacuar hacia las salidas de emergencia del túnel', 'Retroceder para salir del túnel', 'Encender las luces altas y esperar'],
    respuestaCorrecta: 1,
    explicacionTexto: 'En un túnel, el conductor debe apagar el motor inmediatamente para evitar acumulación de gases, activar luces de emergencia, evacuar a los pasajeros hacia las salidas de emergencia del túnel (señalizadas con luces verdes), dejar las llaves puestas para que el vehículo pueda ser movido y no usar ascensores.',
    urlAudio: null,
    dificultad: 'dificil',
    licenseTypes: ['clase_a2'],
  },
];
